---
title: "STSP Draft 12.17.2018"
geometry: margin = 1in
output:
  pdf_document: default
  word_document: default
fontsize: 12pt
---

\section{Introduction}

<!--[[Collective performance intro sentence]] The nature of work has become increasingly interpersonal. Organizations almost universally utilize some form of group structure to accomplish tasks and meet objectives. For nderstanding the processes behind group performance--> 

Many are familiar with the infamous Challenger explosion of 1986, when a failure during launch led to the death of seven astronauts. Subsequent investigations into the incident determined that there were noticeable signs suggesting that the shuttle was not ready for launch. Scientists had ignored the cautions raised within the agency during the months before the incident. Differing views within the organization related to whether the burden of safety should have been placed on proving the shuttle unsafe versus proving the shuttle safe prior to launching were suppressed. The incident etched into national memory the steeps costs of groupthink during group decision making. Another nationally covered incident involved SEAL Team Six following their removal of Osama Bin Laden. The team intensively trained for three days to carry out Operation Neptune Spear, working in tandem to identify hostile threats, deal with unexpected complications (e.g., helicopter crashes), execute their task, and extract relevant intelligence related to national interests. Their success effectively illustrated the immeasurable value of group cohesion and communication. Almost everyone is familiar with emergency rooms, wherein teams of doctors, nurses, and often medical students work together to quickly patch injuries and save lives. Working in an unpredictable environment forces medical teams to adapt to everchanging situations with everchanging stakes, ranging from routine stitching to systemic organ failure. From the extreme to the routine, these collective performances reflect the importance of group processes that either impair or empower group cohesion, communication, and decision making. 

Currently, most group processes are evaluated through the lens of the Input-Process-Output (IPO) heuristic (Santoro, Dixon, Chang, & Kozlowski, 2015; McGrath, 1964). The process function represents a critical component of collective performance, describing the manner by which teams meet the demands of the task to generate viable output. The flexibility of the heuristic allows for the incorporation of mediators, moderators, and a host of predictors to describe the path that teams take when completing their task, and the influences that can facilitate or inhibit their performance. In addition, the model links tasks and outcomes through a pathway, which introduces the notion of temporality. That is, the IPO assumes that relationships between task inputs, group processes, and outputs follow a temporal sequence. While the initial IPO model only assumed temporality, modern variations explicitly address dynamics through feedback loops, episodic-transaction models, and other recursive representations of group process (Santoro et al., 2015). Thus, current research on collective performance offers a potent literature advocating the importance of dynamic group processes. There exist numerous calls to action that point out the need for increased research on collective process dynamics.From McGrath (1986) to Kozlowksi & Bell (2003) to Cronin, Weingart, & Todorova (2011), the past 30 years of collective performance reviews have persistently noted the need to examine group dynamics. While the flexibility, accessibility, and conceptual strength of the IPO heuristic has carried the field to a much richer understanding of temporality and group processes, ultimately the heuristic cannot fully explain the dynamic nature of collective performance. Indeed, given the wealth of literature on teams and groups, it is strange that little exists on the nature of group process antecedents and dynamics (Cronin et al., 2011). Santoro et al. (2015) have proposed the dearth of knowledge in these areas can be attributed to an overreliance on the IPO model.

Though flexible enough to conceptually incorporate task cycles, episodic models, recursive relations, and feedback loops, the IPO framework presents some fundamental drawbacks when used to understand the temporal nature of group processes. The simple IPO model depicts correlational relationships that are not truly dynamic (Santoro et al., 2015). Recent versions of the model begin to advance understanding of dynamic influences on team structure, effectiveness, and performance, but such models still do not have the ability to estimate group dynamics. These limitations stem from the difficult nature of longitudinal data collection and the lack of formalization within the IPO. Kozlowski and Chao’s (2018) most recent review of the literature notes that “team research has largely relied on cross-sectional, static designs that cannot capture emergence or process dynamics directly” (p. 577). Measuring longitudinal factors in situ often requires invasive and intensive data collection procedures. As a result, most of the field relies on cross-sectional sampling (Kozlowski & Chao, 2018). IPO models that introduce dynamic mechanisms are not easily captured in such cross-sectional samples. More recent research seeks to ameliorate this problem by utilizing simulation techniques to illustrate and predict group processes over time. Such computational models provide greater opportunities to capture group dynamics. However, the lack of formalization within the IPO framework hinders these techniques, which require computation of group inputs, outputs, and intermediate states; terms that hard to estimate using heuristics. Thus, the influences of memory, history, and other autoregressive features inherent to group processes are hard to estimate using IPO models. Therefore, we seek to advance the gap in literature by providing a model to evaluate collective performance that holds similar conceptual utility and flexibility as the IPO, and is also computationally tractable enough to estimate of group dynamics. To that end, we outline some qualities central to group dynamics and two current frameworks for evaluating the temporal features of group processes. Finally, we integrate the current frameworks with concepts from control theory to generate a new theoretical framework that allows for estimation of group processes.   

\section{Qualities of Group Dynamics} 

#Multi-level
Team processes manifest over time. They are influenced by the past history of the team and influence the future directions that the team takes. Process dynamics can be described at local- or global-levels. The local-level refers to the activity of group constituents, which lead to global-level behavior (norms, identity, etc.). Global-level behavior, in turn, influences future local-level activity. Both levels are influenced by contextual dynamics related to the system and environment that shape the trajectory of the group over time. Two key concepts stemming from this conceptualization of dynamics are trajectories and recursion. The former proposes that groups are bound by their histories. That is, conditions of the group at a future time point are bounded by their initial or previous conditions. Recursion comes from the multi-level perspective of groups. Local-level activity creates global-level activity, which then constrains local-levels at future time points. 

Consider safety climates. The micro-decisions that groups make informs how much priority they place on safety. This can result in climates, or shared perceptions regarding safety procedures. The climate then influences future directions that the employees take with regards to their safety. For example, consider a team that is faced with the dilemma of a defective part (Hoffman et al., 2017). They can either continue operations with a makeshift part that poses a safety risk, or wait for a fully functional replacement. The team must make a decision whether to prioritize productivity over safety by continuing operations with a relatively unsafe part instead of waiting for a replacement. Should they choose to continue operations instead of waiting for a fully functional replacement, the team essentially prioritizes productivity over safety. Over time, such micro-decisions (i.e., local-level behavior) emphasizing productivity over safety leads to shared perceptions (i.e., global-level climate) that productivity holds more importance than safety. Going forward, the team is more apt to continue operations with makeshift parts, even if this poses risks. Here, the concepts of trajectory and recursion are evident as micro-decisions create climates that influence future micro-decisions.  

#Regulation
This multi-level perspective is often combined with other dynamic properties such as regulation and collective memory to represent group processes. Regulatory theories describe the trajectory of teams as hovering around an equilibrium point. That is, groups will evaluate their progress towards a goal or state and adjust their behavior according to how far away they are from their perceived equilibrium. In the case that they are over-performing, they will shift behavior downwards; in the case that they are underperforming, they will shift their behavior upwards. For example, an underperforming sports team may seek to increase effort to match the opposition. 

In some cases, over or underperformance can cause equilibrium points to shift in accordance to the nature of the discrepancy. In the case of underperformance, the goals may shift downwards to meet the perceived ability of the group to meet the task; the converse can occurs in the case of over-performance. If a team realizes they have no chance to beat the opposition, they may shift their goal downward and try to lose by a small rather than large point differential.  

In addition, the group may change goals entirely over time. For example, the goal of a basketball team may be to score as many points as possible during the game to develop a lead over the opposition. Should the team hold a comfortable lead, the goal may shift from scoring points to holding possession of the ball in order to conserve energy. In this case, the goal shifts from scoring points to energy conservation. The self-regulating perspective inherently considers group processes as changing over time. The behaviors that teams engage in depend on where they lie in relation to their current goal at a specific moment in time.

#Collective memory
Collective memory describes an understanding of shared group knowledge. Shared understanding in teams develop as members learn how to interact and engage with each other, forming schemas about their individual roles and responsibilities. The schemas help precipitate adaptive responses by the group during unpredictable situations. Medical teams serve as exemplars of team adapativity. Patients showing familiar symptoms during surgery can alert the medical staff to the possibility of complications. With knowledge of how the complication presents itself and how to handle the patient's symptoms, the team can respond appropriately to mitigate the chance of fatality. In such a dynamic environment, having a shared representation of everyone's functions allows individuals to better coordinate and support each other. Surgeons who are unfamiliar with a complication may not realize that it is the anesthesiologist's responsibility to treat the patient. The unfamiliarity causes "stop and think" moments, which detracts from the speed and level of coordination, often to the detriment of the team. Thus, a group likely cannot respond to a situation that is wholly novel with the same level of adaptiveness that they would for a situation that is extremely familiar. In other words, teams are changing entities that respond to the situational factors within the boundaries of their history. 

#Modern Frameworks
#IMOI
As the field has transitioned to more dynamic representations of group processes, various IPO models have developed to represent the temporal factors. The Input-Mediator-Output-Input (IMOI) model moves towards a more thorough representation of dynamics by introducing a loop that links outputs to future inputs, which influence future mediators, and subsequent outputs (Ilgen et al., 2005). The representation is similar to the original model, but extends the IPO framework in two important directions. First, the IMOI substitutes process for mediator, to move research away from input and process variables and understand process itself; which generally requires examination through mediators. For example, Ilgen et al. (2005) note that many constructs important during group processes are not truly process, but emergent states. As groups work and interact with each other self-evaluative and regulatory behaviors lead to the emergence cognitive and affective states. Such states are not actually behavioral processes, but nonetheless, greatly affect team performance and warrant inclusion when discussing collective performance dynamics. 

In addition, the structure of the IPO model suggests that the path from input to output is linear; however, group processes are often more complex. The intervening moderators and mediators that facilitate or inhibit group processes are better conceptualized in the IMOI framework than the IPO. 

Second, adding "input" after "output" speaks to the temporal features of team performance. The initial IPO model implies a single-cycle path, which the field has largely moved away from. More recent research has examined outputs as antecedents of future inputs and processes, but even early pioneers of the IPO have acknowledged the need to identify feedback loops and other dynamic processes. The IMOI moves to an explicit representation of such temporal features by following outputs with inputs of the future developmental cycle. That is, future inputs are represented as the result of current outputs, and their preceding processes. The IMOI then classifies each cycle into tripartite: Forming, Functioning, and Finishing stage. Each stage also contains affective, behavioral, and cognitive mediators that reflect the process of collective performance. The forming stage reflects early team interaction, with trust, planning, and structuring respectively referring to affective, behavioral, and cognitive mediators. The functioning stage marks when the team gains experience working with each other and processes occur through bonding, adapting, and learning mediators. The finishing stage ends one episode of the team's overall developmental cycle. 

The episodic-stage representation of team development cycles allows for the evaluation of concepts related to history, constraints, memory, and other dynamic-related properties. The IMOI easily allows for feedback loops and modeling of psychological mechanisms that explain why groups function better than others, rather than simplistic causal chains that state which groups are better than others. Though arguably the most powerful representation of group dynamics in the literature, the IMOI model remains a heuristic. Ultimately, it does not provide a formal representation for evaluation of group inputs, outputs, and intermediate states. Absent of longitudinal samples that illustrate causal chains, many of the  propositions under the IMOI framework remain untested or measured through cross-sectional samples. Computational and agent-based modeling techniques would prove greatly useful in provide generative validity of the theoretical relationships posed by IMOI. Unfortunately, such procedures require mathematical approximation of hypothesized relationships. As a heuristic, the IMOI does not provide for easy computation. Computational models require "algorthimic specficity", with precise and exactly specified sequences that detail the sequence of theorized phenomena (Sun, 2008). Formalization is necessary to ensure transparency and testability of theoretical processes (Gigerenzer, 2008). At their core, inputs, outputs, and mediators are informal labels to represent the process of collective performance and as such provide vague information as to specified sequences of collective performance. Though researchers may employ analytical methods that can be subsumed under the catch-all labels in the IMOI, they are hard-pressed to specify in precise details various group processes using this representation. This issue occurs largely because the IMOI - much like the IPO - does not provide a mathematical framework needed to formally evaluate dynamic properties. 

#Dynamic Team Composition Model
Mathieu et al. (2014) developed a team composition equation designed to address some of the previously raised issues and compute team performance. First identifying the four major types of teams, the authors developed a mathematical framework that could for the relative contribution of each member - and the group performance as a whole. The traditional personnel model considers the individual's competency for their task as a purely additive contribution to the overall group performance. In other words, group performance is the sum of each individual's performance. The second model includes teamwork considerations. This personnel model reflects inherent disparities of task contributions by team member positions. Pilots contribute inherently more towards reaching the destination than flight attendants. By nature of their position, surgeons contribute more to operations than nurses. This is represented in an equation weighting the individual contributions to the task. Instead of considering performance as the sum of each individual's performance, performance is now the sum of each individual's weighted performance. The weights are determined by how important the individual's position is to the task. Pilots and surgeons would have high weights, while attendants and nurses would have lower weights. 

The Team Profile model views the team more holistically. Members are indexed within a team profile, which is then related to performance. Core ideas to this compositional approach include identifying team requisite KSAOs and diversity factors. Each individual has KSAOs that are indexed according to a diversity idex or mean score values, which contribute to the team profile. For example, if doctors need to treat a patient that does not speak English, having someone on the team who can speak other languages may prove requisite to providing proper treatment. In this case, the knowledge of foreign languages is not necessarily tied to the position of doctor, nurse, etc. but still aids in team performance. That is, the knowledge adds to the team profile relevant information that aids collective performance. In the evolving equation, effectiveness is not only considers the competencies and relative importance of individuals and their positions in relation to the task, but also how each member contributes to the team as a whole, and how this team profile contributes to the task. 

The fourth, "relative contribution", model incorporates the notion of interdependency. While the prior models considered how each individual contributed to the team and the task, they did not assess the interdependent nature of collective performance. Individuals are often aided by or wholly dependent on the completion of one part of the task by other individuals. In the course of product launch, developers must wait on designers, product testers must wait on developers, and so forth. Here, Mathieu et al. (2014) introduce the linked-member exchange term. This equation incorporates the relative importance of each member's KSAO in relation to the position of other members on the team. E.g., the importance of a member's KSAO related to product design in relation to the impact that the product developer can provide to the task. By describing group processes in terms of the relative contribution of each team member to the task, the model takes a compilational perspective. It is important to note that this equation theoretically provides for nonadditive influences. In other words, group outcomes are not necessarily the additive results of individual contributions towards a task; this theoretically allows for computation of emergent states. The relative contribution model incorporates the multi-level theory inherent to group dynamics. In addition, the equation introduces the concept of temporality, suggesting that such interdependencies and relative contributions are subject to change at different time points. 

While informative, this approach has some deficiencies. For one, each time point is treated as an independent cross sectional sample. We can track changes over time in relative contribution and interdependencies, but there is no way to introduce the concepts of constraints, history, or any regulatory processes. In addition, while the authors posit that the relative contribution model allows for computation of emergent states, the equation does not allow for simulation or data to test this proposition. Thus, this equation does not truly introduce the concept of dynamics.

\section{Borrowing from control theory: the basic state-space equation}

Literature on small groups and teams have suggested that a variety of states exist during collective performance. Cognitive states describe processes of evaluating oneself, other team members, and the team itself in relation to task performance. The process involves measuring discrepancies in group effectiveness, the purpose of the group mission, etc. in relation to the desired goal, the boundaries of team abilities, resources, and deadlines, and adjusting effort and expectations accordingly. Attitudinal states describe similar processes that members use to regulate their emotions and attitudes during the course of the performance trajectory. In essence the states represent episodic snapshots of different regulatory processes at a single time point, which are influenced by previous states and influence future states.

It seems logical to borrow from control theory to utilize mathematical frameworks to drive research in states. The state space representation generally models physical systems by integrating inputs and state variables to generate or predict outputs. The state variables are time-variant and evolve iteratively. The general description fits well with the previously described state perspective of attitudes and cognition in group dynamics, and provides a computational tractability that has not been provided in the literature. The general state space equation is $Ax_t + Bu_t = x_{t+1}$. The inputs are represented in the time varying terms $x_t$ and $u_t$, while the process variables are represented in $A$ & $B$. Switching from summation notation used in Mathieu et al. (2014) and formalizing the block diagram provided in Ilgen et al. (2005) using matrices, we can encode all the known characteristics of the system and the team within the four terms. The $A$ matrix can describe the system characteristics that influence the team processes, while the $B$ matrix can represent the specific team processes (e.g. interpersonal, motivational, attitudinal processes). In addition, by utilizing a time-varying paradigm, we can incorporate ideas of memory, trajectory, and evolution through the $x_t$ matrix. Here, $x_t$ refers to the initial inputs and characteristics of the team at an initial time point $t$, while $x_{t+1}$ describes the future state (output) after accounting for the temporal context of the team (historical constraints). The u matrix can correspond to team inputs to the system (KSAOs, interpersonal inputs, etc.). By utilizing matrices, we can include all variables of interest into the terms and account for the contextual, system, and individual-level effects to predict outputs. 

This framework extends the benefits provided using previous equations and heuristics. From the equation, we can easily compute inputs and processes to predict outputs in a dynamic system. Further, the state-space representation allows us to predict not only the overall output, but also the growth of the team in the intermediate states. We provide conceptual examples of its usage in the domain of cohesion, performance, and conflict dynamics.

\section{Example in conflict dynamics}

Conflict resolution occurs as a process influenced by contextual factors, individual characteristics of group members, and system-level influences. Each present state of resolution is constrained by previous states of the process. For example, it is impossible to achieve resolution unless a conflict is acknowledged by the involved parties (Pondy, 1967). If the conflict is not acknowledged by one of the parties, the resolution process itself may not occur. System-level characteristics including the formalized procedure organizations mandate employees to follow can influence the nature of the resolution process (Gelfand, 2011). Contextual factors like culture can influence the method that employees utilize to express their disagreement with each other, or whether they are likely to express a disagreement at all (Lee & Rogan, 1991). Finally, individual characteristics of preferences in communication and emotional expression also determine how conflict is resolved (Weingart et al., 2015). All of these variables are worth investigating simultaneously and tracking over time to predict the likelihood of resolution. Interpersonal interactions can cause individual characteristics to shift, which can be constrained by situational factors like context and history. Teams that effectively resolve conflicts learn and resolve conflicts faster the next time that a similar conflict occurs (REF). That is, the team’s resolution undergoes evolution as effective practices are encouraged and ineffective practices are discarded when conflicts occur.  

From the previous definition of the state-space equation, we can add process variables like organizational procedures and contextual factors like national culture into the $A$ and $B$ matrices. The input variables of individual characteristics are reflected in the u matrix. The $x_t$ matrix represents the initial resolution preferences and point along the trajectory towards resolution. The $x_{t+1}$ then describes the group’s likelihood to resolution at a future time point. Iterating across time points then allows us to track the trajectory of the team towards a resolution. Conversely, we may also notice that the likelihood of resolution is steadily decreasing. Such instances are easily seen in conflict spirals, where each party continues to escalate the conflict until a point that it becomes intractable (Weingart et al., 2015). To date, there does not exist a model that allows for computation of such a process or predictions that incorporate dynamic and recursive influences. The state space equation allows us to further the literature on the described conflict processes by providing a viable method with which to model these dynamics. 
