---
title: "STSP draft 01.23.2019"
geometry: margin = 1in
header-includes: \usepackage{setspace}\doublespacing
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
  word_document: default
fontsize: 12pt
---
#Introduction 

Collective performance reviews persistently note that group processes are dynamic (McGrath; Ilgen; Kozlowski). There is path-dependence or memory: initial dyadic exchanges constrain social perceptions across the rest of the mission; there is feedback and reciprocal influence: task demands influence individual and team performance, which then update the task structure creating new task demands that influence subsequent performance; there is differentiation potential: individual members with unique attributes may (or may not) become more homogeneous over time and/or contribute different resources (Cronin). To account for the dynamic nature of collective performance, researchers require useful theoretical frameworks to guide their work.

The most common lens in organizational science to study collective processes is the Input- Process-Outcome (IPO) framework (Santoro). Although the IPO model captures some fundamental notions of dynamic collective performance, such as feedback, ultimately it is a heuristic – a metaphor with no formal underpinning. In their critique of the IPO heuristic, Matheiu et al. (2017) note that the collective performance literature must “formally incorporate temporal issues” and “revisit the fundamental temporal nature of team evolution and dynamics” (p. 460). In other words, accounting for dynamics requires a mathematically rigorous perspective that is not present in the heuristic version of the IPO. In some respects, this work has already begun. An updated IPO framework now exists (IMOI; Ilgen) and Matheiu et al (2014) presented a recent dynamic team composition model that describes collective performance over time. Though these models push the field in promising new directions, each carries its own limitations that hinder their ability to study dynamics. In this paper, we review three popular frameworks of collective performance (IPO, IMOI, Matheiu dynamic team composition) and discuss their shortcomings. Then, we resolve the limitations by presenting a formal state-space equation that captures the dynamics of collective performance.

#The Original IPO

The original Input-Process-Outcome (IPO) reflected a task contingency approach to group performance, whereby performance was represented in a linear path from team inputs, process, and outcomes (McGrath 1964; Hackman & Morris, 1975). The process function is especially critical, describing the manner by which teams meet the demands of the task to generate viable output.

$Inputs$. Inputs reflect the context in which the team performs, often conceptualized as individual, group, or organizational factors. These factors affect group processes and subsequent effectiveness. For example, individual factors such as KSAOs or personality characteristics of teamwork preferences will affect the outcome of the team. If a member does not have the requisite skill to complete his/her task or does not work well with others, the effectiveness of the team is likely to diminish. Group level inputs such as the size and tenure the team also affect the performance of the team; in general, long tenured groups may perform better than new groups as tenure facilitates cohesion (REF). At the organizational level, supervisory systems (e.g., level of worker autonomy), organizational structure (e.g., flat vs. hierarchical), and environmental resources (e.g., turbulence) influence team processes and outcomes (REF). 

$Process$. The process stage represents the interaction between group members en route to completing the task (REF). These are conceptualized as behaviors relevant to achieving the group’s goal. The literature has identified a wide variety of such behaviors, including conflict, communication, cohesion, and learning (REF). Such factors either facilitate or inhibit the performance of the group. A moderate amount of task conflict benefits performance; similarly, cohesion facilitates communication; team learning leads to quicker responses and increased team adaptiveness (REF). On the other hand, role conflict, decreased trust, and turnover can decrease effectiveness and inhibit group outcomes (REF). The inputs will affect how these processes manifest. Long-tenured groups may have a higher level of cohesion, trust, and less role conflict (REF). In turn, the group processes increase or decrease performance or effectiveness.

$Outcomes$. Outcomes of the group are generally operationalized as team effectiveness or performance. Other conceptualizations view outcomes in terms of attitudes (e.g., job satisfaction) and behaviors (e.g., retention) (REF). These characteristics are the product of group inputs and processes. Following the previous pathway, a long-tenured team promotes cohesion, and subsequently increases retention and performance. 

##Strengths

The main strength of the IPO framework is its accessibility. The flexibility of the heuristic allows for the incorporation of mediators, moderators, and a host of predictors to describe the path that teams take when completing their task, and the influences that can facilitate or inhibit their performance. The notion that a group  works together within some context and produces an outcome relevant to their overall goal, provides an intuitive and powerful perspective of collective performance. In addition, the framework links tasks and outcomes through a pathway, which introduces the notion of temporality (Ilgen). That is, the IPO assumes that relationships between task inputs, group processes, and outputs follow a temporal sequence. 

##Weaknesses

There are several limitations of the IPO paradigm. The three most relevant criticisms pertain to its conceptualization of process, lack of attention to dynamics, and inability to model long-term changes in collective performance. 

The IPO conceptualizes process as a single stage event. This does not account for the mediational pathways that underlie the temporal features of performance. Following the previous example, long-tenured groups may promote trust, through increased communication. The communication and trust then promote cohesion, which in turn, relates to higher effectiveness. The process pathway is often what is truly of interest to researchers, rather than single process variables. In addition, process often contains differential effects (REF). Trust may increase between members of the same seniority and status more easily than between lower-level and higher-level members (REF). This holds implications for other process variables and outcomes.

This limitation is further illustrated when discussing temporal features of collective performance. Feedback loops, episodic models, and recursive relations, which are critical to team effectiveness are difficult to incorporate into the IPO. For example, the previous example posed a team with high performance as a result of increased communication, trust, and long-tenured members. From this point in the team’s development, the performance (output) can change future inputs and processes. High performance can lead to increased member retention, communication, and trust. Here, the outcome has become the input, affecting future inputs and processes. The reciprocal influence present in collective performance is lost under the IPO framework. In addition, the IPO is hard pressed to include components of memory. Consider whether a team member first encounters an agreeable team member versus a disagreeable member. The initial exchange will likely influence how the team performs as a whole, at least from a short-term perspective. Positive exchange promote cohesion and facilitate trust, whereas negative exchanges will likely lead to a slow such processes (REF). Finally, because the IPO considers the lifespan of a group to be a single cycle event (i.e., groups operate in a context to reach a final outcome), there is little discussion of the team trajectory. Do members converge in their knowledge and behavior as they develop shared mental representations of the task? How does the initial context and performance affect this trajectory? Such questions are of interest to those conducting research on small groups, but remain unanswerable under the IPO framework. 

Longitudinal research using the IPO framework can measure some of these dynamic properties, but often requires invasive and intensive data collection procedures. Recent technological advances have led to increased usage of computational and agent-based modeling to study dynamic and longitudinal changes in teams (Kozlowski & Chao). Because the IPO remains a heuristic, its lack of formalization mutes the effectiveness of these modeling practices. Formalization is necessary to ensure transparency and testability of theoretical processes (Gigerenzer, 2008). At their core, inputs, outputs, and mediators are informal labels to represent the process of collective performance and as such provide vague information as to specified sequences of collective performance. Though researchers may employ analytical methods that can be subsumed under the catch-all labels in the IPO, they are hard-pressed to specify, in precise details, various group processes using this representation. This issue occurs largely because the IPO does not provide a mathematical framework needed to formally evaluate dynamic properties. 

#An Updated IPO: The IMOI Model

As the field has transitioned to more complex representations of group processes, various IPO models have developed to represent the temporal factors (Ilgen). The Input-Mediator-Output-Input (IMOI) conceptualizes the developmental cycle of a team as a tripartite stage model: Forming (IM), Functioning (MO), and Finishing (OI). Each stage contains affective, behavioral, and cognitive mediators that reflect the process of collective performance. The IMOI represents an extension of the IPO. The notions of input and outcome are largely the same; the difference between the models stems from their conceptualizations of process. Whereas the IPO generally views process in terms of behavior, the IMOI considers affective and cognitive mediators as well. The IMOI also builds on the IPO by offering stages of development during the team’s performance cycle.

##Forming Stage

The forming stage refers to the intial interactions between team members. The stage characterizes the early period of the performance cycle, when members are not yet fully connected and the group structure is developing.

\textit{Affective mediator: trust}. For trust to form, they must perceive that others are competent and that the group goal is aligned with their individual goal. (Ilgen) conceptualize these constructs as potency and safety. These represent the affective components of the team, and reflect how the team members feel about each other. 

\textit{Behavioral mediator: planning}. Planning occurs as groups gather information and use it to develop a viable strategy. Gathering information is a broad term to encapsulate the behaviors of information seeking and exchange. From the gathered information, members begin to coordinate and communicate strategies for completing the task. 

\textit{Cognitive mediator: structuring}. Finally, groups develop collective norms and individual roles in the structuring phase of the forming stage. These are developed through shared mental models and transactive memory systems. The former refers to common cognitive elements among team members, and the latter refers to the members’ unique cognitive elements. (Ilgen) note that the literature is divided on which promotes effectiveness more. Some scholars posit that SMM yield higher performance, whereas others suggest effectiveness occurs through compartmentalization (TMS). In any event, both refer to the cognitive elements of team members, their schemas of themselves in relation to the task and their understanding of each other.

Both gathering information and strategy development are facilitated by higher levels of potency. Similarly, increased information exchange and coordination promote SMMs and subsequent performance. Taken together, there is a substantial body of literature suggesting that these mediators interact with each other to promote group formation (for more discussion of this literature see Ilgen et al., 2005). 

##Functioning Stage

The functioning stage marks when the team gains experience working with each other; here, processes occur through bonding, adapting, and learning mediators. 

\textit{Affective mediator: bonding}. Bonding extends beyond trust by incorporating feelings of attachment to the larger collective. That is, whereas trust reflects the feeling of wanting to work together, bonding reflects the feeling of wanting to stay together (Ilgen). Bonding requires successful management of membership diversity and conflict (REF). Moderately heterogeneous teams containing token members and subgroups reduced cohesion; similarly, social conflict often negatively relates to commitment and cooperation (REF). 

\textit{Behavioral mediator: adaptation}. Adaptation refers to two behavioral mediators: performing in novel conditions and sharing the workload (REF). The former refers to the ability of members to continue successful performance when the group context suddenly shifts, and the latter reflects the willingness of members to shoulder the burden together in the face of high task demands. 

\textit{Cognitive mediator: learning}. Team cognition improves through learning processes, both from dissenting members and high performing members. Dissenting members provide unique perspectives that serve to further members’ insight into each other and the task (REF). Learning from the most knowledgeable and highest performing member on the team works to increase the knowledge base of others on the team, in turn, strengthening their performance. 

The IMOI, much like the IPO, implies a temporal pathway. Events in the forming stage affect events in the functioning stage. Groups are unlikely to bond if they do not trust each other. Teams are hard pressed to adapt if they are not willing to gather and exchange information. If the team does not have a shared understanding of the task and their respective roles, it will prove difficult for members to learn from each other. 

##Finishing Stage

The finishing stage ends one episode of the team’s overall developmental cycle. (Ilgen) note that there is a dearth of research on this stage of a team’s lifespan. There are many reasons for a team’s dissolution: teams may disband because of interpersonal tensions, low performance, or the nature of the task (i.e., short-term contract teams). Often, as in the IPO model, the finishing stage is conceptualized in terms of team effectiveness. Here, the IMOI posits that the outcome of one cycle influences the input of the following cycle, hence, the finishing stage captures the OI portion of the model. Indeed, there is evidence to suggest that performance at Time 1 predicted aspects of potency and subsequent performance at Time 2. 

##Strengths

The advantage of the IMOI framework largely roots in the explication of the temporal pathway of the team. The notion that teams go through different stages during their performance cycle (formation, functioning, finishing), extends the IPO by explicitly incorporating temporal features of teams. The initial IPO model implies a single-cycle path, which the field has largely moved away from. More recent research has examined outputs as antecedents of future inputs and processes. The IMOI moves to an explicit representation of such temporal features by following outputs with inputs of the future developmental cycle. That is, future inputs are represented as the result of current outputs, and their preceding processes.

Finally, the IMOI substitutes process for mediator to move research away from input and process variables and understand process itself. This perspective generally requires examination through mediators as causal chains. In addition, the structure of the IPO model suggests that the path from input to output is linear; however, group processes are often more complex. The intervening moderators and mediators that facilitate or inhibit group processes are better conceptualized in the IMOI framework than the IPO.

##Weaknesses

Though there are commendable incorporations of dynamic features, the IMOI model suffers from the same weaknesses that plague the original IPO conceptualization. For one, the IMOI remains a heuristic. The inability to formalize processes under the paradigm results in the inability to model temporal features of performance through computational and agent-based methods. Though the model can allow for feedback loops and recursive influences, absent of longitudinal samples that illustrate causal chains, many of the propositions under the IMOI framework remain untested or measured through cross-sectional samples. This is not to necessarily criticize cross-sectional research, but rather to point out the limitations of the IPO and IMOI paradigms. Computational and agent-based modeling techniques would prove greatly useful in provide generative validity of the theoretical relationships posed by either model. Unfortunately, such procedures require mathematical approximation of hypothesized relationships. Computational models require “algorithmic specificity”, with precise and exactly specified pathways that detail the sequence of theorized phenomena (Sun, 2008). As heuristics, neither model provides such information. 

For another, the IMOI would treat each member as equally important in relation to the task. For example, when traditional analytical methods through the IMOI, relationship conflict between team members generally contains a single negative regression coefficient in relation to task performance. This is not often truly representative of teams. It is highly likely that the relative contribution of a team lead is larger than the relative contribution of a junior member or new hire. Thus, a conflict with a team lead should yield a correspondingly larger negative impact on task performance. This differential weighting is not easily or often accounted for in research that utilizes either the IPO or IMOI framework, but is nonetheless crucial to consider when predicting collective performance.

Similar to the IPO, the notions of initial exchanges affecting performance pathways are neglected. While the IMOI tries to address ideas of reciprocal influence, the model views the influence in terms of outcomes affecting inputs. This approach neglects the direct effect of outcomes on future processes and outcomes. That is, OI directly affects both the IM and the MO stages. Taken together, the IMOI has furthered the field’s understanding of process, but perhaps not from an entirely dynamic perspective.

#New Directions: Dynamic Team Composition Model

Mathieu et al. (2014) developed a dynamic team composition (DTC) equation designed to address some of the previously raised issues and compute team performance. First identifying the four major types of teams, the authors developed a mathematical framework that could account for the relative contribution of each member - and the group performance as a whole. Thus, the DTC equation served as a shift away from the IPO heuristic and utilized a more formalized approach to evaluating group processes. Here, we outline the four models of teams presented in the study and describe their integration in Mathieu et al. (2014). We then describe some of the advantages and shortcomings present in this model. 

\textit{Simple Personnel Model}. The traditional personnel model considers the individual's competency for their task as a purely additive contribution to the overall group performance. This is a naive perspective of performance; each individual's contribution is expected to have uniform impact on the outcome. In this model, group performance is the sum of each individual's performance. 

\textit{Teamwork Personnel Model}. The second model includes teamwork considerations. This personnel model reflects inherent disparities of task contributions by team member positions. For example, by nature of their position, surgeons contribute more to operations than nurses. This is represented in an equation weighting the individual contributions to the task. Instead of considering performance as the sum of each individual's performance, performance is now the sum of each individual's weighted performance. The weights are determined by how important the individual's position is to the task. Surgeons would have high weights, while nurses would have lower weights. 

\textit{Team Profile Model}. The Team Profile model views the team more holistically. Members are indexed within a team profile, which is then related to performance. Core ideas to this compositional approach include identifying team requisite KSAOs and diversity factors. Each individual has KSAOs that are indexed according to a diversity index or mean score values, which contribute to the team profile. For example, if doctors need to treat a patient that does not speak English, having someone on the team who can speak other languages may prove requisite to providing proper treatment. In this case, the knowledge of foreign languages is not necessarily tied to the position of doctor, but still aids in team performance. In the evolving equation, effectiveness not only considers the competencies and relative importance of individuals and their positions in relation to the task, but also how each member contributes to the team as a whole, and how this team profile contributes to the task. 

\textit{Relative Contribution Model}. The fourth, "relative contribution", model incorporates the notion of interdependency. While the prior models considered how each individual contributed to the team and the task, they did not assess the interdependent nature of collective performance. Individuals are often aided by or wholly dependent on the completion of one part of the task by other individuals. Here, Mathieu et al. (2014) introduce the linked-member exchange term. This equation incorporates the relative importance of each member's KSAO in relation to the position of other members on the team. Finally, the equation introduces the concept of temporality, suggesting that such interdependencies and relative contributions are subject to change at different time points.

##Strengths

With respect to the IPO and IMOI, the DTC model furthers our understanding of performance in some areas, and takes a step back in others. The first substantial gain from the DTC is the notion of differential potential. Team members have various skills that do not always contribute uniformly to the task. The ability to compare the relative contributions of individuals to the task is a novel insight not explicitly provided by the IPO or its variants. In addition, the DTC represents constructs as terms in an equation. This approach provides a level of algorithmic specificity, which advances our ability to model team phenomena. The DTC also discusses the concept of properties changing over time. 

##Weaknesses

Mathieu et al. (2014) posit that “what Formulas 8 illustrates is that the relationship between team members’ competencies and their linked performances and teamwork will likely develop and change over time” (p. 147). Unfortunately, the equation fails to accomplish how and why these relationships change.  Though introducing a formal conceptualization for temporality in teams is useful and worth noting, there is no way for research to meaningfully discuss dynamic processes under the DTC other than saying that teams change over time. For instance, we can note that team members may have differential contributions, but will be unable to understand why their contributions may change over time. We can see interdependencies change - either teams become more connected or disaggregated, but cannot understand how processes and outcomes like cohesion and performance influence future team processes and task demands, which change interdependence. Because the DTC represents each time point as independent cross sections rather than dependent sequences, there is no way to evaluate the concepts of constraints, history, or any related dynamic properties.

In other words, it is possible to see that the team evolves, as the model provides for representation of performance trajectories; however, it is hard to see how the team evolves. Path dependencies are ill incorporated into a paradigm that treats each performance cycle as an independent cross-section. For instance, team learning is a dynamic property; groups learn about each other and the task as they work together (REF). We cannot understand how learning changes over time, how initial interactions may inhibit or facilitate future team learning, or at which points learning is most useful. Through the DTC, we may note that individuals’ KSAOs are increasing or that team coordination is rising, but we cannot understand how these increases are furthering future increases. Such concepts of self-reinforcing and self-limiting feedback loops are ignored. We may notice that a group’s knowledge base is converging towards homogeneity through the course of multiple performance cycles, but we cannot understand how cohesion and communication are perhaps facilitating such convergence. 

Indeed, this inability to understand how process affects output may be the reason why the output of the DTC equation is uninterpretable. It is intuitive to conceptualize team effectiveness as the sum of individual and team contributions, but effectiveness itself is undefined. Through the DTC, we sum individual and team KSAO’s, their relative contributions, their interdependencies, and other characteristics to yield an undefined value. While we can model performance trajectories, the DTC offers little in the way of conceptualizing what performance (or outcomes) mean and how they relate across different teams.  
 
#A state-space representation of collective performance

The IPO, IMOI, and DTC have significantly contributed to our ability to evaluate and analyze performance. The former two illustrate the need for models that can flexibly represent the myriad of psychological and contextual performance influences, while the latter puts forth a viable model with which to formally estimate and predict performance. Though the three have pushed the field to greater understanding of temporality and performance processes, there exist substantial shortcomings with both approaches. The IPO and IMOI are heuristics, which are hard to formalize for computational models - a practical need for a field interested in longitudinal research. In addition, most of the investigations of performance through the IPO and IMOI lenses suggest uniform effects of factors like conflict or cohesion on team members, and uniform contributions of the team members to the task. On the other hand, the DTC does account for differential contributions, but does not account for dynamics. To redress these issues, we sought to incorporate concepts from both paradigms to develop a dynamic model of collective performance. 

In this effort, we present a state-space equation of collective performance dynamics. The state-space representation generally models physical systems by integrating inputs and state variables to generate or predict outputs. The variables are time-variant and evolve iteratively. This approach formalizes the IPO and IMOI approach by requiring researchers to provide a defined pathway for performance cycles. In addition, including time-variant terms allows for the performance cycles to be viewed as dependent sequences. This is a dynamic perspective of the DTC model, as it incorporates notions of path dependence, reciprocal influence, and differentiation potential. Through the state-space equation, we can index team members based upon their contributions and their KSAOs, while also accounting for the group’s context and their evolving processes. These concepts are key to furthering our understanding of dynamic performance.

The general state space equation is $A_tx_t + B_tu_t = x_{t+1}$. Inputs are represented in time varying terms $x_t$ and $u_t$, while the process variables are represented in $A$ & $B$ matrices. Switching from summation notation used in Mathieu et al. (2014) and formalizing the block diagram provided in Ilgen et al. (2005) using matrices, we can encode all the known characteristics of the system and the team within the four terms. This presents an equation that integrates and extends the concepts of the DTC and IMOI in a less cumbersome and computationally efficient manner. 

\textit{State vector}. Broadly, the term $x_t$ is a "state" vector, which represents all of the characteristics of the \textit{initial} team state. This vector indexes current output (i.e., performance metric) as well as the intermediate states that lead to this output. Consider a manufacturing plant that needs to produce pins. The path to production might include cutting the pin to size, sharpening the end, attaching a pinhead, and finishing the pin. In this example, $x_t$ would reflect the initial state  characteristics: the number of cut pins, sharpened pins, pins with a head, and finished pins. The $x_t$ vector then serves as an autoregressive anchor, from which we build the performance trajectory and evaluate team dynamics.

\textit{State matrix}. The $A$ matrix represents the processes that directly affect the state. Absent of outside influences, how do the outcomes of interest change over time? Consider the example of an insurance agement who sells life insurance. Let's say that the agent starts out with ten sold policies. If the agent does nothing, it is unlikely that outside influences will change the number of sold policies. In other instances, this may not hold true. Things grow and decay. Machines and buildings naturally wear down over time. Through the years, organizational practices and procedures become more crystallized. Absent of any psychological or physical influences, such factors affect performance. These are encoded in the $A$ matrix. From the previous example, consider the effect of machine decay. As the utility of pin-making machines decreases over time, the team effectivness (i.e., number of finished pins), will also decrease. This property is encoded within the $A$ matrix.

\textit{Transition matrix}. The $B$ matrix represents the effects of task contributions towards changing the state. Generally, completing one step of a process decreases the number of unfinished steps. Sharpening a cut pin increases the number of sharpened pins, but decreases the number of cut pins; finishing pins decreases the number of unfinished pins. Each step in the process contributes towards changing the state in some manner. The transition matrix reflects these changes.

\textit{Process matrix}. Team processes and inputs are encoded in the $u$ matrix (e.g., KSAOs, motivations, interpersonal processes, etc.). Individuals work together to make pins; one person cuts, another sharpens, and a third attaches the head and finishes the pin. Through working together, individuals may become more cohesive. Through specialization, their competencies may increase. These characteristics may interact with each other in some manner as the group works together to make pins, and these interactions may change over time. Thus, their variation and subsequent impact on performance across time are reflected in the $u_t$ matrix.  

\textit{Output-input vector}. Finally, the outputs are recorded in the $x_{t+1}$ matrix. This term is similar to the OI portion of the IMOI model, but extends the conceptualization by providing a meaningful prediction of all the characteristics of the state at a future time point (not just outcomes). In this manner, the state space model extends both the IPO and DTC frameworks by representing both the output (i.e., finished pins) along with the intermediate states of the pin-making process (i.e., cut and sharpened pins). 

##Contributions

From the state-space equation we can see that the intial context (i.e., $A$ and $x_t$) affects the outcome ($x_{t+1}$). From the literature we know that self-reinforcing feedback loops are common (e.g., conflict spirals). Processes encoded in $u_t$ affect future processes ($u_{t+1}$) and outcomes ($x_{t+1}$), which in turn affect processes and outcomes at time $t+2$. We also note that these influences are interrelated and affect process and outcome differently as a function of member's expertise and their importance to the task (i.e., relative contribution). 

The IMOI conceptually addresses the first two notions of path dependence and reciprocal influence, but does not provide a formalized method with which to evaluate those temporal features; the IMOI also does not address the notion of differential effects. On the other hand, the DTC addresses the latter point of differentiation and offers a formal perspective of performance, but cannot estimate any effects of path dependence or feedback. Our conceptualization allows for an understanding of these features from both a conceptual and computational perspective. Rather than independent cross-sections, the equation conveys a detailed sequence of path dependencies, which provides for autoregressive features inherent to collective performance. 

From the state space model, we can easily compute the dynamic interactions of inputs processes, and outputs. Further, the state-space representation allows us to predict not only the overall output, but also the growth of the team in the intermediate states. We provide conceptual examples of its usage in the domain of cohesion, performance, and conflict dynamics.


 
