---
title: "STSP_draft_11.21.2018"
header-includes:
    - \usepackage{setspace}\doublespacing
output: pdf_document
---

\section{Intro}

From McGrath (1986) to Kozlowksi & Bell (2003) to Cronin, Weingart, & Todorova (2011), the past 30 years of collective performance reviews have persistently lamented the lack of research on group dynamics. Indeed, some of the reviews have gone so far as to suggest that the field studies “group statics” rather than “group dynamics” (McGrath, 1986; Cronin et al., 2011). While the field has built tools to understand concepts essential to examining dynamics (e.g.  recursion, dependence, evolution, and multi-level theory), research in the area is still scant; a phenomenon that remains puzzling (Cronin et al., 2011). 

\section{What is Dynamics? Definition and some key properties} 

Dynamics can be described at local- or global-levels. The local-level refers to the activity of group constituents, which lead to global-level behavior (norms, identity, etc.), which in turn influences future local-level activity. Both levels are influenced by contextual dynamics related to the system and environment that shape the trajectory of the group over time. Two key concepts stemming from this conceptualization of dynamics are trajectories and recursion. The former proposes that groups are bound by their histories. That is, conditions of the group at a future time point are bounded by their initial or previous conditions. Recursion comes from the multi-level perspective of groups. Local-level activity creates global-level activity, which then constrains local-levels at future time points. From these core concepts, the literature has received multiple calls to action for advancement of theory and practice in evaluating group processes. 

Further research has incorporated additional concepts of equilibria and regulation, memory, and self-similarity to describe the nature of groups as dynamic systems. Regulatory theories describe the trajectory of teams as hovering around an equilibrium point. That is, groups will evaluate their progress towards a goal or state and adjust their behavior according to how far away they are from their perceived equilibrium. In the case that they are over-performing, they will shift behavior downwards; in the case that they are underperforming, they will shift their behavior upwards. In some cases, over or underperformance can cause equilibrium points to shift in accordance to the nature of the discrepancy. In the case of underperformance, the goals may shift downwards to meet the perceived ability of the group to meet the task; the converse occurs in the case of over-performance. This perspective inherently considers the processes of group activity and tracks them over time. 

Group memory describes how situations can provide cues that alert members and groups as to whether the situation is novel or similar to previous situations (Burke, et al., 2006). The cues can then precipitate adaptive responses by the groups or members towards the situation. Again, this concept views teams as changing entities that actively respond to the situational factors within the boundaries of their history. A group likely cannot respond to a cue that is wholly novel with the same level of adaptiveness that they would for a cue that is extremely familiar. 

The conceptualization of groups performing on a trajectory has led to evaluations of groups by their states. There exist numerous types of states (e.g. cognitive, affective, motivational, etc.). In general, the states describe the time-variant properties of groups that are influenced by inputs, processes, outcomes, and context (Burke, et al., 2006). Emergent states result as a function of lower-level states previously mentioned. Integrating the state-level perspective with the ideas of equilibrium and memory suggests that states operate in cyclical rhythms in accordance with the history of the group. 

\section{Calls to action}

Criticisms regarding usage of cross-sectional data, self-report measures, and models of simple, unidirectional relationships have spurred the field to call for conceptualizations of groups as dynamic and adaptive complex systems (Cronin et al., 2011). However, there remain striking similarities between the calls to action in the initial McGrath (1986) article and a more recent Kozlowski and Chao (2018) critique. The former paper offered that 1980’s research had little to say about the mechanisms of change, let alone their antecedents and consequences. In addition, there was little research on the multi-level structure of groups, how performance was influenced by environmental factors related to higher-level organizational and lower-level individual factors. Moving forward, the field advanced multi-level theory, and pushed for more system-based models of dynamic groups (Cronin et al., 2011). However, Kozlowski and Chao’s most recent review of the literature notes that “team research has largely relied on cross-sectional, static designs that cannot capture emergence or process dynamics directly” (p. 577). It would appear as though our advancements have not fully bridged the gap between theoretical and empirical research. While there exist a number of models that speak to the temporality of group behavior and provide heuristics as to the nature of dynamic processes, few exist that are computationally tractable. 

\section{Some current models: Mathieu’s Temporal Team Composition Model and the IPOI} 

Mathieu et al. (2014) developed a team composition equation designed to address some of the previously raised issues and compute team performance. His equation assesses the sum of the relative importance of each members KSAO and their interdependencies in relation to the task. By describing group processes in terms of the relative contribution of each team member to the task, the model takes a compilational perspective. In this equation, group outcomes are not necessarily the additive results of individual contributions towards a task, which allows for computation of emergent states. This incorporates the multi-level theory inherent to group dynamics. In addition, the equation introduces the concept of temporality, suggesting that such interdependencies and relative contributions are subject to change at different time points. While informative, this approach has many deficiencies. For one, each time point is treated as an independent cross sectional sample. We can track changes over time in relative contribution and interdependencies, but there is no way to introduce the concepts of constraints, history, or any regulatory processes. Thus, this equation does not truly introduce the concept of dynamics.

The IMOI model moves towards a more thorough representation of dynamics by introducing a loop that links outputs to future inputs, which influence future mediators, and subsequent outputs (Ilgen et al., 2005). From this conceptualization, outputs are constrained by initial inputs and mediators. This allows for the evaluation of concepts related to history, constraints, memory, and other dynamic-related properties. In addition, the move from process to mediators allows researchers to track changes in a complex fashion. The model allows for feedback loops and modeling of psychological mechanisms that explain why groups function better than others, rather than simplistic causal chains that state which groups are better than others. Though arguably the most powerful representation of group dynamics in the literature, the IMOI model remains a heuristic. Ultimately, it does not provide a formal representation for evaluation of group inputs, outputs, and intermediate states. That is, though researchers may employ analytical methods that incorporate the heuristic representation of group dynamics, the representation does not provide a mathematical framework needed to formally evaluate dynamic properties. 

\section{Borrowing from control theory: the basic state-space equation}

Literature on small groups and teams have suggested that a variety of states exist during collective performance. Cognitive states describe processes of evaluating oneself, other team members, and the team itself in relation to task performance. The process involves measuring discrepancies in group effectiveness, the purpose of the group mission, etc. in relation to the desired goal, the boundaries of team abilities, resources, and deadlines, and adjusting effort and expectations accordingly. Attitudinal states describe similar processes that members use to regulate their emotions and attitudes during the course of the performance trajectory. In essence the states represent episodic snapshots of different regulatory processes at a single time point, which are influenced by previous states and influence future states.

It seems logical to borrow from control theory to utilize mathematical frameworks to drive research in states. The state space representation generally models physical systems by integrating inputs and state variables to generate or predict outputs. The state variables are time-variant and evolve iteratively. The general description fits well with the previously described state perspective of attitudes and cognition in group dynamics, and provides a computational tractability that has not been provided in the literature. The general state space equation is $Ax_t + Bu_t = x_{t+1}$. The inputs are represented in the time varying terms $x_t$ and $u_t$, while the process variables are represented in $A$ & $B$. Switching from summation notation used in Mathieu et al. (2014) and formalizing the block diagram provided in Ilgen et al. (2005) using matrices, we can encode all the known characteristics of the system and the team within the four terms. The A matrix can describe the system characteristics that influence the team processes, while the B matrix can represent the specific team processes (e.g. interpersonal, motivational, attitudinal processes). In addition, by utilizing a time-varying paradigm, we can incorporate ideas of memory, trajectory, and evolution through the $x_t$ matrix. Here, $x_t$ refers to the initial inputs and characteristics of the team at an initial time point t, while xt+1 describes the future state (output) after accounting for the temporal context of the team (historical constraints). The u matrix can correspond to team inputs to the system (KSAOs, interpersonal inputs, etc.). By utilizing matrices, we can include all variables of interest into the terms and account for the contextual, system, and individual-level effects to predict outputs. 

This framework extends the benefits provided using previous equations and heuristics. From the equation, we can easily compute inputs and processes to predict outputs in a dynamic system. Further, the state-space representation allows us to predict not only the overall output, but also the growth of the team in the intermediate states. We provide conceptual examples of its usage in the domain of cohesion, performance, and conflict dynamics.

\section{Example in conflict dynamics}

Conflict resolution occurs as a process influenced by contextual factors, individual characteristics of group members, and system-level influences. Each present state of resolution is constrained by previous states of the process. For example, it is impossible to achieve resolution unless a conflict is acknowledged by the involved parties (Pondy, 1967). If the conflict is not acknowledged by one of the parties, the resolution process itself may not occur. System-level characteristics including the formalized procedure organizations mandate employees to follow can influence the nature of the resolution process (Gelfand, 2011). Contextual factors like culture can influence the method that employees utilize to express their disagreement with each other, or whether they are likely to express a disagreement at all (Lee & Rogan, 1991). Finally, individual characteristics of preferences in communication and emotional expression also determine how conflict is resolved (Weingart et al., 2015). All of these variables are worth investigating simultaneously and tracking over time to predict the likelihood of resolution. Interpersonal interactions can cause individual characteristics to shift, which can be constrained by situational factors like context and history. Teams that effectively resolve conflicts learn and resolve conflicts faster the next time that a similar conflict occurs (REF). That is, the team’s resolution undergoes evolution as effective practices are encouraged and ineffective practices are discarded when conflicts occur.  

From the previous definition of the state-space equation, we can add process variables like organizational procedures and contextual factors like national culture into the $A$ and $B$ matrices. The input variables of individual characteristics are reflected in the u matrix. The $x_t$ matrix represents the initial resolution preferences and point along the trajectory towards resolution. The $x_{t+1}$ then describes the group’s likelihood to resolution at a future time point. Iterating across time points then allows us to track the trajectory of the team towards a resolution. Conversely, we may also notice that the likelihood of resolution is steadily decreasing. Such instances are easily seen in conflict spirals, where each party continues to escalate the conflict until a point that it becomes intractable (Weingart et al., 2015). To date, there does not exist a model that allows for computation of such a process or predictions that incorporate dynamic and recursive influences. The state space equation allows us to further the literature on the described conflict processes by providing a viable method with which to model these dynamics. 


