---
title: "STSP Intro 12.12.2018"
header-includes:
    - \usepackage{setspace}\doublespacing
output: pdf_document
---

\section{Intro}

Most are familiar with the infamous Challenger explosion of 1986. Subsequent investigations into the incident determined that there were noticeable signs suggesting that the shuttle was not ready for launch. Scientists had ignored the cautions raised within the agency during the months before the incident. Differing views within the organization related to whether the burden of safety should have been placed on proving the shuttle unsafe versus proving the shuttle safe prior to launching were suppressed. The incident etched into national memory the steeps costs of groupthink during group decision making. Most are also familiar with SEAL Team Six, who were instrumental in ultimately removing Osama Bin Laden. The team intensively trained for three days to carry out Operation Neptune Spear, working in tandem to identify hostile threats, deal with unexpected complications (e.g., helicopter crashes), execute their task, and extract relevant intelligence related to national interests. Their success effectively illustrated the immeasurable value of group cohesion and communication. Almost everyone is familiar emergency rooms, wherein teams of doctors, nurses, and often medical students work in tandem to quickly patch injuries and save lives. From the extreme to the routine, each of these collective performances reflect the importance of group processes that either impair or empower group cohesion, communication, and decision making. 

Currently, most group processes are evaluated through the lens of the Input-Process-Output (IPO) heuristic (Santoro, Dixon, Chang, & Kozlowski, 2015; McGrath, 1964). The process function represents a critical component of collective performance, describing the manner by which teams meet the demands of the task to generate viable output. The flexibility of the heuristic allows for the incorporation of mediators, moderators, and a host of predictors to describe the path that teams take when completing their task, and the influences that can facilitate or inhibit their performance. In addition, the model links tasks and outcomes through a pathway, which introduces the notion of temporality. That is, the IPO assumes that relationships between task inputs, group processes, and outputs follow a temporal sequence. While the initial IPO model only assumed temporality, modern variations explicitly address dynamics through feedback loops, episodic-transaction models, and other recursive representations of group process (Santoro et al., 2015). Thus, current research on collective performance offers a potent literature advocating the importance of dynamic group processes.  

Though flexible enough to conceptually incorporate task cycles, episodic models, recursive relations, and feedback loops, the IPO framework presents some drawbacks when used to understand the temporal nature of group processes. The simple model depicts correlational relationships that are not truly dynamic (Santoro et al., 2015). Recent versions of the model begin to advance understanding of dynamic influences on team structure, effectiveness, and performance, but such models still do not have the ability to estimate dynamic constraints. That is, many constraints related to memory, history, and other autoregressive features inherent to group processes cannot be estimated through models based on the IPO heuristic. In addition, IPO models that introduce dynamic mechanisms are not easily captured in cross-sectional samples, which still constitute the majority of group research. This is often the result of inherent invasiveness and intensiveness of longitudinal data collection (Kozlowski & Chao, 2018). Advances computational and agent-based modeling, should ameliorate some of the problems with longitudinal data collection by estimating and illustrating processes over time using simulation techniques. However, though these methods of dynamic modeling provide greater opportunities to capture group dynamics, they also require computation of group inputs, outputs, and intermediate states, which are hard to formalize using heuristic models like the IPO. 

The conceptual strength and accessibility of the IPO heuristic has carried the field to a much richer understanding of temporality and group processes, but ultimately the heuristic cannot fully explain the dynamic nature of collective performance. Indeed, given the wealth of literature on teams and groups, it is puzzling that there exists little knowledge on the nature of group process antecedents and dynamics (Cronin et al., 2011). Santoro et al. (2015) have proposed the dearth of knowledge in these areas can be attributed to an overreliance on the IPO model. Therefore, we seek to advance the gap in literature by providing a model to evaluate collective performance that holds similar conceptual utility and flexibility as the IPO, and is also computationally tractable enough to estimate of group dynamics.
