---
# https://crsh.github.io/papaja_man/index.html

title             : "Opportunities and Recommendations for Structural Interdependence Measures and Indices"
shorttitle        : "INTERDEPENDENCE INDICES"

author: 
  - name          : "Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "316 Physics Rd #348, East Lansing, MI 48824"
    email         : "email"
  - name          : "Author2"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "Michigan State University"


author_note: |
  Author1, Department of Psychology, Michigan State University; Author2, Department of Psychology, Michigan State University.

abstract: |
  Structural interdependence, or the resources and workflows as well as goal and reward systems that connects team members, tasks, and jobs, is a thriving area in organizational science. Emerging evidence across multiple fields suggests that interdependence is a fundamental component to many aspects of workplace functioning. Its operationalization, though, both with respect to measures in empirical studies and indices across various theories, has yet to receive an integrated discussion. This paper reflects on how the constructs and ideas subsumed under structural interdependence are assessed and indexed to guide management research in this area. We provide a taxonomy of measurement devices and indices that fosters the alignment of theory and measurement, point out discrepancies and assumptions, describe unanswered questions, and present actionable next steps for research. In short, our paper begins a conversation about structural interdependence measurement best practice. 

keywords          : "Structural interdependence, task, outcome, initiated, received, measurement, theory"
wordcount         : "102"

bibliography      : ["refs.bib"]
nocite            : '@wageman_as_2005; @ashworth_computational_2007; @van_der_vegt_team_2000; @ariel_team_2000'

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/', echo = FALSE, warning = FALSE, message = FALSE)
```


```{r child = 'interdependence_1_intro.Rmd'}
```


```{r child = 'interdependence_2_self_report.Rmd'}
```

```{r child = 'interdependence_3_indices.Rmd'}
```

```{r child = 'interdependence_4_discussion.Rmd'}
```


\newpage

# References
```{r create_references}
r_refs(file = "refs.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}