---
output: pdf_document
---
# What is Dependency

In reviewing and producing a taxonomy for measures of dependency, it is important to discuss what dependency is, or at least what concepts are included in our conceptualization of dependency. Various terms are used to discuss concepts related to dependency. For example, interdependency has often been referred to in the organizational literature. In this paper, we primarily use the term 'dependency' and do not make any finer distinction between terms such as dependency and interdependency. Interdependence is a broad concept that has been defined in a variety of ways (Van de, 1976); however, there is not a single definition that appears to adequately cover the breadth or depth of this concept (Pennings, 1974). Nothing that interdependency is particularly difficult to define, Pennings proposed that there are at least four distinct types of interdependency: 1) task interdependency, 2) role interdependency, 3) social interdependency, 4) skill interdependency. These categories broadly describe dependency as a relationship between tasks, roles, or individuals. 

Pennings went on to discuss how dependency can be described as a network of connections between elements at one of these "levels" (i.e. tasks, roles, etc.). He suggested that the categories of dependency he discussed could be extended to include relationships between elements at different "levels" (e.g. role-to-task connections). Thus, according to Pennings, indices of dependency would include indices that measure how interconnected tasks, roles, social structures, and/or individuals are. We will rely heavily on Penning's conceptualization of dependency to determine what measures to include in our review of dependence indices. Specifically, Pennings definitions for interdependency includes such concepts as cooperation (rrr), coordination(rrr), collaboration(rrr), teamwork (rrr), subtask matching (Stiner, 1972), and task workflow prerequisites relationships(rrr), to name a few. 

Dependency relationships are often directional (i.e. something depends on something else). For the sake of clarity, we will refer to the thing that depends on something the object of dependency, and the thing that it depends on the source of dependency. Thus a dependency relationship can be described in terms of how an object depends on some source.

We do not claim that this is the only way or the best way to conceptualize dependency; it is simply a workable starting point that is broad enough to encompass its numerous guises in the literature. The purpose of this paper is primarily to facilitate and start discourse on the topic of dependency in collective performance. We do so by providing a framework that can be used to evaluate existant measures dependency and applying this framework to a review of such indices. To this end, Penning's categorization of dependency appears to be a useful starting point.
