---
output: pdf_document
---
#Dependency in Teams

Various researchers have expressed that interdependency is an essential and defining characteristic of teams and team structures. Neuman and Wright (1999) emphasized the importance of interdependence to teams, stating that, "teams consist of two or more individuals that can be characterized by high task interdependence," (p. 377). In a separate definition of teams, Kozlowski and Ilgen's (2006) illustrate the importance of interdependence:

\textit{A team can be defined as (a) two or more individuals who (b) socially interact (face-to-face or, increasingly, virtually); (c) possess one or more common goals; (d) are brought together to perform organizationally relevant tasks; (e) exhibit interdependencies with respect to workflow, goals, and outcomes; (f) have different roles and responsibilities; and (g) are together embedded in an encompassing organizational system, with boundaries and linkages to the broader system context and task environment (p. 79)}

Taken together, dependency is 1) a defining characteristic of teams in its own right and 2) intrinsic to other qualities and processes necessary to the definition and function of teams (e.g. interactions, shared goals, workflow processes, etc.). 

In support of dependency as a necessary quality of teams, research has shown that dependency is key in differentiating types of teams. Specifically, two of the three components in Lee and colleague's Team Descriptive Index (TDI) are horizontal and vertical interdependence (Lee et al., 2015). According to the theoretical foundation of the TDI, a team with very strong horizontal dependence will have highly specialized team members; therefore team members must rely heavily on each other in order to do their individual jobs properly. This is an example of what Newman described as task interdependence. In contrast, a highly vertically dependent team may require very precise timing in performing some basic task; thus, a pattern of strong, centralized decision-making and leadership is important to maintain synchronization. Individual performance in this type of team is highly dependent on its centralized leadership. In both cases, the amount and type of dependency are important factors in defining the team and its function. 

The TDI demonstrates the importance of dependency on categorizing teams. Additionally, the TDI illustrates discrepancy in how dependency can be conceptualized in the literature. The two types of dependency measured by the TDI are related to the same concept but makeup clearly distinct constructs. Often this type of disparity can be found in how dependency is used in the literature.

Support for dependency importance to team process is found in Steiner's influential typology of task types (rrr 1972). Many of the categories and distinctions (Divisible and Unitary Tasks; Disjunctive, Conjunctive, and additive, etc.) described by Steiner can be described partly in terms of differences in the interdependency of tasks, and task outcomes. For example, the outcome performance of Disjunctive tasks is dependent on the best performance of members of the team on that tasks, and the performance of conjunctive tasks is dependent on the worst performance of a member on a team. Steiner further theoreises about how individuals are matched with subtasks of a divisible task. This concept of matching and relationships between subtasks and task performance is futher realted to the notion of depednecy.

In further support dependency's importance to team processes on outcomes, research has proposed that dependency has important impacts on performance and efficiency. Mathieu proposed a model for collective performance that provides theoretical insight into the processes by which dependency may impact team effectiveness (Mathieu, Tannenbaum, Donsbach, & Alliger, 2014). The mathematical model they present is a compilation model of collective performance where each team member's contribution is summed up. The model accounts for the fact that individual roles in a team may be highly dependent on other roles. For example, in a football team, the performance of a wide receiver who catches the ball is highly dependent on the quarterback who is throwing the ball; if the quarterback cannot throw the ball, the wide receiver will never catch. On the other hand, if the wide receiver is poor, the quarterback may still have options such as running the ball, thus the quarterback's performance is not as dependent on the wide receiver as the reverse. Mathieu's concept of 'linked member performance' is a theoretical construct of how much each member of the team contributes to team performance when these interdependencies are considered, and the total team effectiveness is calculated as an aggregation of these 'linked member performance' values.

Empirical work has validated Mathieu's theoretical claim that dependency is tied to performance. For example, dependency and its related sub-constructs (interdependence, coordination, cooperation, teamwork, etc.) have been empirically linked to numerous individual and outcomes, including: individual well-being (rrr), failure rates (rrr), reward effectiveness (Persall, 2010), the impact of role ambiguity (rrr Beauchamp, 2001), and general performance (Wageman, 1995; Shiflett, 1972). Dependency clearly is central to teams and team processes.

Thus, the study of dependency relationships is crucial to forming a deeper understanding of the processes that drive and influence collective performance. Unfortunately, this endeavor is currently hindered by the lack of a common framework. The studies referenced previously use vastly different measures of dependency, including analysis of task structures, self-reported data, and observations of team member interaction. Without a clear taxonomy for dependency measures, it is unclear how measurements of dependency relate to each other or to theoretical frameworks (e.g. Mathieu's model of team effectiveness). It is crucial that organizational science develop a structure whereby these measurements can be clearly compared side by side. Development of such a typology would elucidate investigations into the impact of dependency on teams and team outcomes, as well as enhancing theory development.
