---
title             : "Outline for Dependency Index paper"
shorttitle        : "Dependency Outline"

author: 
  - name          : "Daniel Griffin"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

# Introduction
## Examples of Dependency
### Pin Example
### Coding Examples
### Opening a door
## Definition of dependency
## Outcomes associated with dependency
## Dependency in (or not in) our literature
# Measuring Dependency
## O'Brioin
## Mathieu
## Syntactical, Work, Logical Dependency
## Path Dependency
# Comperison of Dependency measures
# Conclusion
