---
output: pdf_document
title: Dependency Intro
---
# Introduction

For decades the notion of dependency has emphasized within the organizational science literature (rrr); in particular, interdependency is a key defining factor of teams (Kozlowski & Ilgen, 2006; rrr). As Kozlowski and Bell stated, "Recognition of the central importance of team workflow, and the task interdependence it entails, to team structure and process is a... key characteristic of the organizational perspective on workgroups and teams," (Kozlowski & Bell, 2003 page 455). Despite the central importance of dependency in defining teams and determining how they function, there exists no framework by which various measures of dependency can be compared, and there are no guidelines providing structure to the discussion of dependency's impacts on team performance. We propose a two-dimensional taxonomy for dependency indices. The first dimension, Index level of analysis, divides indices between those that measure an individual's characteristics and those that measure a team's characteristics. The second dimension is based on the how the structure of dependency is conceptualization. In the structur dimension, dependency indices are split between those that measure 1. The magnitude of dependency, 2. the inter-relatedness of dependency, and 3. the sequential nature of dependency within a team. Such a taxonomy will greatly facilitate teams research. In the absences of a recognized framework to differentiate various concepts related to dependency, there has been construct proliferation where various similar constructs have repeatedly emerged in the organizational literature without any clear way of comparing or differentiating them. We suggest that research of team processes has been inhibited in part by the lack of such a framework. A clear taxonomy for measures of dependency within teams will allow greater coordination within research, help to resolve conflicting findings, lay a foundation for future theory and empirical investigation.

Further highlighting the importance of dependency in teams, the nature of dependency in a team has been used to both define taxonomic differences between various types of teams, and various categories of tasks. Hollenbeck et al. provided the Three-Dimensional Team Scaling Model (3DTSM), a framework for describing types of teams. This model focuses largely on types of dependence within teams (Hollenbeck, Beersma, & Schouten, 2012). Two of three components, 'horizontal differentiation' and 'skill differentiation', are directly related to the concept of dependency, as Lee et al. (2015) illustrated by incorporating these dimensions into the Team Descriptive Index (TDI) as 'horizontal interdependency' and 'vertical interdependency'. 

Similarly, Stiner (1974?rrr) provided a typology for tasks which largely differentiated tasks based on how performance outcomes are dependent on individual member performance. Performance on Stiner's "Disjunctive tasks" is determined by the strongest individual in the team while "Conjunctive tasks" are tasks where the weakest member of the team defines the team's overall performance. In both cases, team members must depend on each other to perform well. It is striking that in addition to being a defining factor of teams,  dependency can both differentiate different types of teams and tasks.

From the organizational literature, dependency is both ubiquitous and vital to understanding teams, tasks, and their associated outcomes. It notable that there is little agreement on how dependency should be described, let alone measured. To put this issue into perspective, consider the debate over interrater agreement that transpired over the last four decades. There are two primary indices used to measure interrater agreement, rwg and kappa. Since 1984 (rrr), researchers have pored over these two indices, writing numerous articles that articulate the merit of one over the other (RRR). The result of this debate has served to organize the literature on interrater agreement and provide a consensus on how to approach interrater agreement within the context that it appears. Dependency, by stark contrast, has many indices and has had no analogous discussion organizing the literature. Despite many references to the importance of dependency and numerous indices of dependency, no discussion has clarified how these measures relate, or what is, in fact, being measured. As a result, there is no existing framework by which these indices can be analyzed in a clear, well-defined manner. Without a taxonomy to categorize different indices of dependence, it is unclear if the various papers that purport to study dependency are, actually studying the same construct. In the absence of a unifying lexicon, continued dependency research is in danger of making incorrect generalizations and identifying inconsistencies where none exist.

A well-defined taxonomy of dependency measures will contribute to future team research in various ways. First,  a formal classification system will greatly facilitate future scientific communication about the concept of dependency. Clear articulation of what is being measured will allow for greater confidence in comparisons and replications of results. Second, the clarity afforded by an established taxonomy could also resolve seemingly contradictory results. For example, interdependence has recently been associated with both positive and negative measures of performance (rrr). It is possible that a formal taxonomy of dependency would allow researchers to discriminate which measures of dependence are positively associated with performance and which are negatively associated.  Third, a formalized taxonomy for dependence will promote theory generation. The newfound ability to identify specific types of dependence will enable researchers to consider its important impacts on team outcomes in finer detail and with more depth than our current organizational lexicon allows for. 


The goal of this paper is to provide a theoretically grounded framework that can be used by researchers who study dependency in organizations. It is our hope that this taxonomy will provide greater unity to the discussion of organizational dependencies and incite further direct discussion of this important topic.
