---
output: pdf_document
---
# A Taxonomy for Dependency

## Overview of the Taxonomy	

Numerous measures of dependency have been used in the organizational literature. Many of these indices are closely related; others measure concepts that are very different. We aim to provide an objective framework which can identify and describe these similarities and differences in the measurement of dependency, thus bringing greater clarity to research. The two primary dimensions of our taxonomy are 1) Level of Analysis, 2) Structure Type. These dimensions were developed from observations of existing measures of dependency in the literature and represent what we deem a natural categorization of dependency index characteristics. As both dimensions of the taxonomy can be objectively defined in terms of networks, we employ a network perspective of dependency, clarifying distinguish made by the taxonomy.

## Network representation of dependency
Defining dependency as a relationship between individuals and/or tasks leads naturally to the use of a network perspective of team dependencies (Pennings, rrr). The connections within these dependency networks are dyadic dependency relationships and the nodes in the network are people, roles, and/or tasks. With the exception of self-report and observational measures, all indices of dependency we have encountered explicitly make a reference to such a network. This fact is strongly suggestive of the utility of a network perspective of dependency. 

We find it surprising that despite how indices used in the literature can be naturally described in terms of a network, there is little direct discussion of the theoretical implications of a network perspective of dependency. Despite explicitly measuring network characteristics, many indices are described without reference to the implications or interpretations of the network characteristics that they are based on. We suggest that dependency may be better studied by explicitly exploring the theory of dependency networks. The network conceptualization of dependency has various implications which will be the work of future research to investigate. For the purposes of the present paper, it is sufficient to note that a network perspective can help to clarify criteria for each of the categories defined by the proposed taxonomy.

## Dimensions of Dependency Taxonomy

### Index Level of Analysis

Dependency is measured as either a characteristic of an individual or of a team. It is informative to distinguish between indices of dependency which measure an individual's (role's /task's) dependence on external factors and a team's overall dependence. Multi-level theorists have demonstrated the merit of having tools that split a construct into organization, team, and individual level components of a construct (rrr). The index level of analysis has important implications for dependency.

Index Level of Analysis refers to the level of analysis for the index itself. The objects or sources of dependency for relationships incorporated into a given dependency index may be at the individual, team, or even organization level, regardless of the index level of analysis. For example, an index may aggregate various dyadic dependency relationships to a team level index. In this case, the object and source are both at the individual level for each dependency relationship, but the index aggregates the impact of these individual-level relationships to the team level and is a team level index. Many individual level indices of dependency can be aggregated to the team level. According to the network perspective, individual level indices are measures of some value that applies to a single member of the network; team level indices are measures of a value that applies to the entire network at once.

#### Individual Level
Individual-level indices are important in cases where the focus is on identifying how dependency impacts a single person, role, or task. In practice, an individual level index could be used, for instance, in job design or selection. Positions that have a high degree of person-to-person dependency would require a socially skilled individual compared to positions with little or no person-to-person demands. As another example, individual indices could be used to analyze task structures and the potential for failure propagation. Tasks that must be completed before other tasks could be identified through individual dependency indices, and managers could allocate extra resources to ensure that these essential tasks do not get messed up.

Individual-level indices often use measures of a dependency network that are specific to a single member of the network. There is often a separate value for these measures for each member of the network. For example, the in-degree of a dependency network member (i.e. the number of other members a given member is dependent on) may be an important part of an individual dependency index. This could be calculated as a separate value for each network member.

#### Team Level

Team level indices focus on general impacts across the team or network. Team level indices may be useful from, for instance, to a manager. A team that has a high degree of dependency may need to be restructured to reduce coordination, cooperation, and collaboration costs. Administration or management could use such measures to identify teams of concern. These indices are general and take a macroscopic look at dependency compared to individual level indices.

Team level indices often use measures of a dependency network that are specifically shared across the entire network. There is only one value for these measures of a network for the entire network, For example, the density of a dependency network (i.e. ratio of existent dependency relationships in the network to possible relationships) may be an important part of a team dependency index.

### Structure Type
The structural dimension to the taxonomy splits indices based on the core conceptualization of how a dependency network should be measured. The methods used to evaluate dependency structures can be split into three categories: 1) Magnitude, 2) Interrelatedness, 3) Sequential. Each category has a unique measurement methodology and theoretical implications. Notably, these distinctions can be identified without employing a network perspective, but this perspective is particularly useful in clarifying the distinctions between these categories.

As will be discussed below in greater detail, magnitude indices are focused on the strength and quantity of dependency relationships, Interrelatedness indices measure the propensity of dependency relationships to follow certain patterns, and sequential indices measure the way in which dependency relationships 'chain together'. Identifying the central structural characteristic that defines an index of dependency is important because it illustrates how dependency is being conceptualized in the given context. Depending on the theoretical basis for a study some dependency indices structure types will be more appropriate than others.

While the core structural characteristic used in an index is valuable to consider, it has the potential to introduce some confusion and must be appropriately approached. Specifically, when evaluating an index's core structure type, there can be considerable ambiguity. An index of dependency may, for instance, use more than one network characteristic in its computation. This would leave room for different interpretations of how the index is incorporated into the taxonomy. Consider a dependency index that is primarily based on measuring clustering (an interrelatedness characteristic), but incorporates in-degree (a magnitude characteristic) as well. A researcher may interpret magnitude as a more prominent role in the index's function than interrelatedness. Because of this potential for ambiguity, it is important to be aware of the various network characteristics used to calculate an index when differentiating between indices. Generally, indices appear to fall clearly into one of the given categories, but we propose in cases of potential ambiguity it would be informative to provide justification interpretation that is employed.

#### Magnitude
Magnitude indices measure characteristics of team dependency that are based on the count, size, or strength of dependency relationships. These indices are calculated without regard to how the dependency connections are structured or distributed within the team. In terms of networks, these are measures that count connections but do not incorporate where connections are in the network at all. 

From a network perspective, individual level indices will likely be based on the count or strength of connections to a single team member (task, role). These indices could include such things as degree (the number of connections that a network member has), in-degree (i.e. the number of connections that the given element is the object of dependency), out-degree (i.e. the number of connections that the given element is the source of dependency), the sum of dependency strengths, and the maximum (average, min, etc.) dependency strength. Team level indices may employ aggregation of an individual index across the team, or use different measures such as edge count (i.e. total dependency relationships in the network), or density (i.e. the ratio of dependency relationships to the total possible dependency relationships). Of these possibilities, in-degree and density seem to be the most common uses. 

An individual magnitude index could be concerned with how the overall demands of balancing requirements and responsibilities impact an object's (i.e. individual's, role's, task's) performance. For example, a survey that determines the percentage of an individual's job is doable independently of the team would be a magnitude index of the individual's dependency on the team. Likewise, an index that measures how many tasks are performed by a specific person is an out-degree based magnitude measure of dependency for the individual. These indices could be helpful in, for example, determining the qualities required to fulfill a role or identifying tasks that require more support.

A team magnitude index will similarly, likely be considered with overall demands imposed by dependency relationships, but in the team as a whole. For example, the same survey described as an individual assessment of how much one individual can perform independently of the team could be given to the entire team and possibly aggregated to determine the percentage of team tasks that can be performed independently. An index of the density of a team's 'advice network' would also be a team dependency magnitude index. These indices could be helpful to administration in structuring teams that have, for instance, low coordination costs.

#### Interrelatedness
Interrelatedness indices measure patterns of dependency in a team. These measures are more focused on the patterns that dependency relationships make than the size, quantity or even quality of those relationships. In terms of networks, these are largely measures of dependency connections' ability to predict the presence of other dependency connections.

From a network perspective, interrelatedness indices measure the strength of a networks pattern. Individual-level interrelatedness indices are a measure of how well a specific person (role, task) fits into a given pattern. One example is reciprocity. If the given individual, A, seeks for advice from someone else, B, how likely (or unlikely) is it that B seeks advice from A. This sort of index could measure the directionality of advice, or influence, in the team. Reciprocity, hierarchy, transitivity, and cycle closure are all network characteristics that can be used to evaluate either individual or team level characteristics. Indices may also define more specific patterns they are interested in. Clustering (or transitivity) related network characteristics appear to be most commonly employed by interrelatedness indices of dependency.

An individual interrelatedness index of dependency could be focused on determining individuals that are contributing too little or too much to the team. For example, a survey could be used to assess if an individual's reciprocity in a network of observed helping behaviors is much lower than the team average. This may indicate that the individual is giving (receiving) much more help than they receive (give). A team interrelatedness index of dependency could assess the impact of team members waiting on each other to finish prerequisite tasks. For example, an index may measure how likely it is that team members are assigned to the tasks prerequisite to other tasks they are assigned. If these relationships are common there will be less coordination wait cost for someone else to finish a prerequisite task. 

Dependency indices that are Interrelatedness focused are concerned with broad patterns of how dependency relationships relate to other dependency relationships. These could be helpful in identifying helpful, or problematic patterns of dependency.

#### Sequential
Sequential indices of dependency are based on how dependency relationships chain together. These indices are not just concerned with what an object (i.e. person, role, task), is dependent on, but what those sources of dependency are themselves dependent on and so on. These indices are considered not just directly what something depends on but what it indirectly depends on. 

In terms of networks, these indices encode ideas such as path length, ancestor sets, progeny sets, and connectedness. Network characteristics that could be incorporated into a sequential dependency index include eccentricity, radios, girth, connectivity, and edge-connectivity, size of ancestor (i.e. all network members that a given object is directly or indirectly dependent on), size of progeny (i.e. all network members that are directly or indirectly dependent on a given object), and node-connectivity (i.e. the size of the minimum number of network members that would need to be removed to split the network into separate components). Instead of focusing on the size or strength of dependency, or patterns directly related to some object (i.e. person, role, task), sequential indices focus on how dependency relationships form chains through the network connecting various network members. Path-length related indices are the most common form of sequential dependency that we have identified.

An individual sequential index of dependency may be concerned with determining how susceptible a specific task is to failure. If the given task, A, is dependent on only one other task, B, a magnitude measure may suggest the risk of some failure impacting A is low; only failure on B would matter. But if B, were dependent on many other tasks, failure on any of these tasks B is dependent on, would propagate to A. 

As another example, a team level sequential index may be concerned with the rate of information propagation in a team. If individuals only depend on certain other team members for information, it is possible that important information may get caught in a bottleneck and dropped. A team sequential index of dependency, may, for example, assess the radius of an information dependency network to determine worst case scenario how long it could take for new information to pass through the system. Another index may measure a team's information dependency network connectivity to assess how many points of communication failure would cause the team to be unable to properly spread new information.

Sequential indices are able to capture higher order, dependency relationships that may have important influences on team outcomes. These indices could be powerful tools to assess the potential for error propagation, problems in information flow, or even the maximum speed the tasks can be completed considering their prerequisite path length. Any time higher-order relationships are theoretically likely to be important, a sequential measure of dependency would be appropriate.
