---
output: pdf_document

---
# Dependency Indices
See Table 1 for how each index fits in the proposed taxonomy.

## Self-report and Behavioral Measures

### Survey and Questionnaire
By far the most common method currently used to measure dependency are self-report measures. These indices very in quality, length and what type of dependency they measure. Self-report questionnaires are by nature dependent on the ability of the individual in question to accurately provide the information requested and thus can be very subjective. Despite their limitations, self-reports generally require minimal knowledge about the tasks and team structure, and require minimal effort on the part of the researcher to use.

#### The Self-Construal Scale (SCS) 
The SCS (rrr) is a good example of a self-report measure of dependency. The SCS focuses on identifying how much an individual generally relies on working with other people. An individual's interdependence and independence are essentially treated as a personality measure in the SCS. The SCS includes items related to one's need and desire to work with others, respect for authority, and also their independence. 

The SCS is an individual level index, measuring primarily direct dependency relationships with no reference to indirect dependencies. The SCS is not concerned with specific tasks and therefor makes up a univariate index. While the SCS does not intuitively fit into the network conceptualization of dependency, the scores provided could be construed as the weights of the connections made by dependency relationships of a single object. In this regard this index is related to the network characteristic of degree-centrality.

The SCS has the advantage that that very little knowledge about the team, work environment, or job is necessary to use it. It is a simple questionnaire that can be sent out, and team structure, and interpersonal relationships do not need to be analyzed directly. Though the SCS is designed as a self-report index it is possible it could be adapted for a supervisor to fill out and conduct the rating if desired. The SCS also can be used as a point of comparison between individuals found in teams of various compositions.

The SCS is fairly limited in that it can only be applied to interpersonal, general dependency. An entirely new scale would need to be developed if a researcher wanted to consider any other type of dependency. The SCS cannot directly really measure characteristics of a team structure or position and is not designed to be specific to one job meaning an individual's responses may reflect their experiences in various jobs over their life time. 

These strengths and weaknesses make it a reasonable index to use but only when measuring an individual's inter-personal dependency, and not in terms of a specific job, team or context.

#### Team Descriptive Index (TDI)
Lee et al.'s  Team Descriptive Index (TDI: rrr) can be used as a measure of a team's overall dependence in two ways. The original intended use of the TDI is to distinguish between types of teams, and it does this by providing a three dimensional team index. Two of the three dimensions are directly related to the notion of horizontal and vertical dependence (Skill Differentiation, and Authority Differentiation). Essentially this questionnaire will provide values that describe how closely a team is reliant on each other, and how much they are reliant on direction from leadership. 

The index is designed for the team level analysis. The concept of horizontal dependence and vertical dependence are not based on some aggregation of individual direct dependencies and likely have various objects of dependency making the TDI an indirect index of dependency. The dependency relationships described appear to be based solely on person-person relationships thus the index is univariate. While the TDI doesn't give a direct way of building a dependency network, it is based on overall level of horizontal and vertical dependency which is related to the network characteristic of density.

The TDI has various advantages. It can be used to categorize different types of teams, comparing the level of dependency between teams. It does require knowledge of the team or teams in question, but does not require direct access to the members of the team in question. It can be filled out by a manager or supervisor, potentially making it easier to use than a survey which must be answered by the members of a team. 

The TDI, like the SCS, is not very flexible. It could not be easily adapted to other uses beyond its original intended use. Another potential drawback is that it requires significant knowledge about the team or teams being studied.

The TDI appears to be a potentially powerful tool for measuring a team's level of dependency in at least two different ways. This tool is not very flexible, and requires expert knowledge, but in the right situation appears to be an ideal tool for studying dependency.

#### General Survey Measures
Various other questionnaires have been implied as an index of dependency. These include everything from single item measures of how much one's job requires the collaboration of others (rrr), to other complex assessments of an individuals need for interdependence in the work place. These indices can either be at the individual level, or surveys of a team as a whole. They can also be direct or indirect indices of dependency. Lastly these indices typically do not fit directly into any network characterization, but could be described as being related to ideas of density for team level indices or degree for individual indices. While both examples described above were univariate indices it is quite reasonable that a survey could be used to address both people and tasks making them bivariate. 

The fact that self-report and questionnaire measures of dependency could fit into any category of the proposed taxonomy is an advantage. While we suggest that indices that objectively look at the structure of a team and its task, may be more objective than self-report measures, these indices have certain advantages. Primarily these are easy to apply. The use and practice of survey research is very well established, and typically has a low cost impact on the subjects of inquiry. Similarly, these typically require minimal fore-knowledge of the team and task structures. These measures also have the advantage that they can be very specific in their targeted type of dependency. It is us believe the self-report measures will, for better or worse, remain the dominant method to measure dependency. We hope that this taxonomy enables researchers to identify specific types of dependencies theoretically important to their study while developing an appropriate questionnaire scale.

Despite the dominance of self-report and questionnaire research, we suggest that the study of dependency will be significantly augmented by the addition of objective measures of team behaviors, and the team / task structural components. In addition to helping differentiate types of dependency measures, we hope this review will demonstrate alternative measures that can be applied in research.

### Behavioral Observation
Various observational measures have been employed to study dependence. Studies have observed behaviors such as helping / backing up behaviors (rrr), and completion of shared responsibilities, and general team interactions. These behaviors are not directly measuring dependency relationships, but behaviors indicative or interdependency. For example a team with a large amount of backing up behaviors clearly has a high degree of dependency in that the performance of individuals in a team influences how well the other can perform. 

Just as the self-report and questionnaire measures of dependency tend to be very specific in the type of dependency they measure, observational measure is very specific in what they measure. For example, helping behaviors are indicative a team that formally or informally has grown to share responsibilities for tasks. A count of helping behaviors will not directly inform a researcher about the complex task to task relationships that are important to a team, however an observational count of time that individuals must 'pass off' a task to another individual in the team, may get at this task to task structure.

Though each behavioral index is unique, generally we expect that they will measure dependency on an individual level. However, individual level counts of behavior, may likely be aggregate to the team level. It also seems likely that behaviors will account entirely for direct dependencies. Behavioral measures could include people and tasks or just one of these object types, thus they could be univariate or bivariate. There easily could be exceptions to this categorization or observational measures of dependency, but this seem like a likely characterization of most observational dependency indices.

Behavioral Observation measures have several strengths. First, they do not rely on the subject opinion of a subject or manager like questionnaires do. With well-trained behavior raters, and inter-rater agreement being assessed, these measures can be very objective. Observational measures are also powerful in that they can target a very specific type of dependency. They have the additional advantage that they do not necessarily need to take any time from the subjects of the study. 

Behavioral observations also have some severe limitations. It is expensive and time consuming to identify behaviors of interest, train raters, analyses inter-rater reliability, and code behaviors. Certain behaviors can be automatically counted through computer programs; however, work is still necessarily to identify behaviors of interest, and clearly demonstrate that machines are measuring the desired behavior. While each behavioral measure is different, generally these indices of dependence will have significantly higher overhead cost as compared to self-report measures. While structural measures may have a similar upfront cost to use, behavioral measures will typically have a much higher continuing cost to them.

We suggest that behavioral measures add a unique component to the study of dependency, but the cost of starting and maintaining an extensive behavioral observation study makes it prohibitive in some cases. Where possible, observational measures add a level of depth to the study of dependency that surveys have difficulty achieving, but they are not ideal for every situation.

## Structural Measures of Dependency
It is important to note that structural measures of dependency are based on information that likely would need to be gathered in one of four ways. Questionnaires, Observed behaviors, Subject Matter Experts, and Team / Job analysis. These indices differ from the indices previously described, in that the questionnaires or observed behaviors would be used to account for a structure of dependencies either between people and or tasks. By contrast the indices previously described largely ignore the structure, and are based on counts of behaviors and perceptions about interdependency in teams.

In the current section we do not focus on the methods used to measure the dependency relationships incorporated into a given index of dependency. Generally any of the four methods listed could be used to collect the data, making this a question of specific application of a given index. We will focus instead on the implications of how each index treats dependency.

For each index, will provide a conceptual background, but only briefly touch on the mathematics used to calculate each index. This is not meant to be a comprehensive discussion of the equations. If the reader wishes a more in depth discussion of any index provided, they are encouraged to seek out the original papers referenced.

### Collaboration and Coordination:
O'Brien proposed a three level system for describing teems with people (level 1) assigned to specific positions or people (level 2) which in turn are assigned specific tasks (level 3). In this framework O'Brien describes three indices of dependency. These are 1. Inter-position Collaboration, 2. Inter-position Coordination, and 3. Inter-Task Coordination (O'Brien, 1967, 1968).

#### Inter-position Collaboration
O'Brien's (1968) index of inter-position collaboration (IPCl) is a measure of how much responsibility for a team's assigned tasks are shared between more than one team member. Thus a team that shares responsibility for all team tasks would have a very high collaboration score. By contrast, a team with one separate task for each team member would have a minimal collaboration score. It is assumed in this framework that each person is assigned at least one task. 

This index is closely related to the TDI's concept of horizontal dependency, or skill differentiation. Consider a team of widget makers. You may have someone responsible for molding the widget parts, someone separately responsible for cutting out the widget parts from the mold, and finally a separate person responsible for putting the parts together. You also could have a situation where all the tasks are performed by everyone. TDI would describe the first situation as having a higher degree of skill differentiation, this corresponds to a lower level of IPCl when compared to the entirely integrated team.

The method for calculating IPCl is fairly simple. IPCl is the roughly ratio of extra task assignments to the total possible number of extra tasks assignments. By extra task assignments, we mean task assignments above and beyond the assumed minimum of each task being assigned at least one person. Thus a team where every task is assigned exactly once would have an IPCl or 0 and a team where every person was assigned to every task would have and IPCl of 1. The equation is given as follows:

$$IPCl = \frac{\sum_{i=1}^n \Big(id(t_i)-1\Big)}{n(m-1)}$$

Where $t_i$ is the $i$th task, $id(t)$ is the in-degree of $t$, $n$ is the total number of tasks and $m$ is the number of people. The simplicity of this index makes it both very useable and potentially very powerful. Additionally, this index has a meaningful 1 and 0 values, which is a significant advantage when attempting to interpret the meaning of a score. 

In a football game, when the defense uses a zone defense there is typically overlap between assigned zones causing shared responsibility for the task of coving the given zone (or players in the zone). A zone defense will thus typically have an IPCl score greater than a man-defense patterns.

This index of dependency is designed to account for the entire team's inter-person collaboration, thus the IPCl is a team level index. An individual's collaboration is characterized by both their direct assignment to a task and indirectly to the assignment of another individual to that task thus IPCl is an indirect index. Both people and tasks are accounted for in the dependency network implied by the IPCl thus it is bivariate. The IPCl is an index based on the concept of network density, basically conceptualizing a highly dependent team as a team with a dense task assignment network. The IPCl is a bivariate team level index of indirect dependency characterized by dependency network density.

Overall the IPCl appears to be a powerful index of dependency. It is both conceptually simple, and mathematically elegant. To our knowledge this index has not been tested for empirical value, but it certainly shows promise. It does require knowledge about how tasks are assigned, but not significantly more information than this. It could be easily calculated from information gathered from a supervisor interview.

#### Inter-position Coordination
The second index proposed by O'Brien is inter-position coordination (IPCd). Whereas O'Brien conceptualized collaboration (IPCl) as a score indicating of how much individuals must work together on the same tasks, inter-position coordination (IPCd) is an index measuring how much the tasks performed by individuals are related. When tasks have specific pre-requisite tasks there are coordination demands that require team members to perform the tasks in the correct order. IPCd is the ratio of these coordination demands that are held within person compared to between person. IPCd is minimal when the tasks performed by one person are completely independent from the tasks performed by another person such that each person can perform their assigned tasks regardless of if the other team members perform their assigned tasks. IPCd is maximized when every task that has a pre-requisite is assigned to different person than the pre-requisite task.

While IPCd is not necessarily equivalent to the TDI's vertical dependency, conceptually they could be related. A team that has a high degree of task coordination demands, likely requires a high degree of centralized direction in order to work smoothly. For an example let us assume we have a widget making team with two people (r1 and r2) and four tasks. Mold widgets (t1), cut widgets from mold (t2), assemble widgets (t3), and test the widgets (t4). Clearly the tasks are interdependent in that t1 must precede t2 and so on. Let us assume that for some reason r1 can only perform t1 and t3, and r2 can only perform t2 and t4. There are significant coordination demands for the team to work smoothly. In a team where r1 can perform t1 and t2, and r2 can perform t3 and t4, there is only one point of responsibility tradeoff and accordingly there is a lower coordination demand for this team.

Mathematically CPTd is the ratio between the number of times a task performed by a specific person must be directly preceded by a task performed by the same person to the total number of times a task performed by a specific person must be preceded by any other task. The method for calculating this index goes beyond the level of this paper, but the method is not overly complicated. 

The lower the IPCd score the more inter-person coordination is required compared to within-person coordination. When there is no interpersonal coordination demands this IPCd will give a value of 1. When half of the coordination demands require inter-person coordination the IPCd will be .5 and so on. Though not specified in O'Brien's original index, it may be worth defining the IPCd for a team where no tasks have pre-requisite tasks as 1 (basically saying if no coordination is required, all the coordination is handled within the individual).

The IPCd is an index of dependency designed to account for the entire team's inter-person coordination, and thus the IPCd is a team level index. An individual's collaboration is characterized by both a person's direct assignment to a task and indirectly based on the relationship between that task and other tasks making IPCd an indirect index. The IPCd accounts for both people and task making it bivariate. Lastly the calculation of IPCd is related to transitivity or clustering (a IPCd score of 1 would indicate perfect transitivity, and a score of 0 would indicate a complete lack of transitivity). The IPCl is a bivariate team level index of indirect dependency characterized by network transitivity.

Inter-position coordination is a somewhat more complicated index of dependency when compared to inter-position collaboration. It does, however, have the simple elegance of an index with inherently meaningful values of 1 and 0. It also takes into account inter task relationships, not just the impact shared tasks. Like IPCl this index requires only basic team structural information and thus would be fairly easy to apply. Overall, IPCd seems to be an appropriate index to use when inter-task relationships and task to person relationships are both important.

#### Inter-task Coordination
Inter task coordination (ITC) is the last index proposed by O'Brien. Inter-task coordination is a measure of task structure complexity. Each task can precede or be preceded by other tasks, this index is a way of formalizing a measure of the complexity of this task-task structure. Tasks that have many pre-requisite tasks clearly are more 'coordination' demands than tasks with no pre-requisite tasks. Likewise, according to the ITC, a task that has a pre-requisite with its own pre-requisites will have a higher coordination demand than a pre-requisite that has no other pre-requisites.  ITC can be characterized as a measure of the coordination demands a given task structure has or a measure of how many ways a chain of tasks can break down, such that a higher ITC score indicates a task structure that would be more completely inhibited by failure to complete a task.

Consider again the widget making team with three tasks - Mold widgets (t1), assemble widgets (t2), and test the widgets (t3). The ITC for this task structure is maximal because t1 must come before t2 etc. A failure on a random task has the largest possible average number of other tasks it would inhibit. By contrast consider a widget making team that has completely independent tasks -  assemble widgets (t1), market widgets online (t2), test new widget designs (t3). In this team, t1, t2, and t3 can be completed in any order. The ITC for this team would be 0.

ITC is calculated as the sum of the path length between every pair of tasks (with 0 for any un-connected tasks). This is maximized when tasks are strung out in a line such that t1 precede t2 etc. This is because the disruption of any one task will halt all tasks after that task. ITC is minimized when there are no inter-task relationships so that the sum of all path lengths between two tasks is 0. The values provide by the ITC are non-standardized, but it would be possible to devise an ITC score by the maximum possible ITC score to standardize it such that the score would be comparable to teams with different task structures and different numbers of tasks. Caution must be taken when using this index to compare different teams.

The ITC is a team level index, though it would be possible to count just sum of all path lengths that lead to a single task to get an individual level index. The ITC incorporates indirect dependencies, because the paths that connect various tasks often include more than just dependencies directly related to the given central object of dependency. The ITC only accounts for inter task relationships and is therefore univariate. The ITC is related to the network characteristics connectivity and path length. Thus the ITC is a team level bivariate index of indirect dependences characterized by network connectivity and pathlength.

If the impact of potential failure propagation is theoretically important, inter-task coordination may be a meaningful index to use, however it is not set up to work with person-to-task interactions as well as task-task interactions. Additionally, the ITC is not necessarily usable as a comparison point between teams with different counts of tasks. This may make other options more ideal for studying dependency.

### Syntactic, Work, and Logical Dependency:
The notion of dependency is of particular interest in the software development teams. Here dependency has been used to describe relationships between code, and relationships between different developer person on the team. Relationships between different code sections are considered task-task relationships because the individual's task is to write the given code. There are five indices which we will consider: Number of Syntactic Dependencies, Workflow Dependency, Coordination Work Dependency, Number of Logical Dependencies, Clustering of Logical Dependencies.

It is worth explicitly noting that although these indices of dependencies have been applied specifically to software development teams and tasks, there is no reason why they could not be applied to other teams and tasks.

#### Syntactic Dependency (SD)
Syntactic Dependency is a name for what is commonly just described as a dependency in software development. Syntactic dependencies are instances where code from one file requires code from anther file. Syntactic decencies often come in the form of instantiating a class, or calling a method declared in another source file. The number of syntactic dependencies is typically calculated using a software tool such as C-Rex (rrr). In a general sense syntactic dependency is simply an individual or team level count of dependencies that a given team or individual has. 

The syntactic dependencies could be applied to interpersonal networks as a count of how many other individuals does a given person work with, or it could be applied broadly to tasks as a count of how many tasks impact the performance of a given task. 

Syntactic dependency is either an individual level index or an aggregated team level index. Syntactic dependencies account for only direct dependencies. SD has traditionally only been applied to univariate dependencies, but potentially could be used for bivariate dependencies (for instance a simple count of how many tasks are assigned to an individual could be considered related to this index). Degree centrality is the central concept of this index. Syntactic dependency is an individual level (or aggregated team level) univariate index of direct dependencies characterized by degree centrality.

#### Workflow Dependency (WFD)
In software development, developers are often responsible for different functions of code. When one developer finishes writing a segment of code, they will typically pass it off to other developers who work on related code to make sure it integrates properly. WFD is based on the concept that the number of times code must be passed off between developers is indicative of the developer's interdependency. A particularly complex project may, for example require each addition to the code base to be checked by various developers because each new addition affects many parts of the code.

Workflow Dependency is a direct measure of the complexity of the development team's formal structure, and indirectly a measure of the complexity of the product being produced. WD is computed in two parts. First a developer-to-developer interrelationships are incorporated into a network were the edges are weighted by the number of times a given developer passed off their work to another developer. Secondly the WFD score for a given code segment is calculated as the maximum degree centrality (from the developer to developer network) for any of the developers who worked on that specific code segment.

WFD can be described in more general terms by replacing code segment with task. Thus WFD is defined as the maximum degree centrality (in the inter-person network) of any team member who worked on the given task. The idea of workflow dependency has important implications to various areas of work and is certainly not specific to software development. WFD is maximized for a given task when that task was worked on / assigned to someone with maximal degree centrality in the inter-person network. WFD is minimized when all team members assigned to a given task have no connections to other team members in the inter-person network. 

WFD is defined for a given task (or code segment). WFD, is an indirect index of dependency because it incorporates inter person dependencies where a task is the central object of dependency. WFD incorporates both people and tasks making it bivariate. Degree centrality is the main network characteristic used to calculate WFD. WFD is a bivariate individual level index of indirect dependency characterized by degree centrality. 

WFD as defined here, has the draw back that it is not necessarily very usable to compare values between different team tasks. This is because the number of members on the team will have a significant impact on the reported value. Additionally there is no clear way to standardize this value. Additionally, WFD requires significant knowledge about how often members of the team must work together, and who all has worked on any given task. This makes WFD difficult to use in many situations. On the other hand, WFD provides a powerful method to measure interdependency in the work flow of team tasks. 

#### Coordination Work Dependency (CWD)
CWD is closely related to Workflow dependency; however, where WFD is an index of the formal pass offs required to submit code, CWD incorporates informal coordination requirements that are present in any team tasks. In a development team, if one developer needs to use specific functionality, they will likely need to informally consult with the developer in charge of that functionality. CWD is a way of leveraging knowledge about how tasks are related to understand dependency within the team.

CWD is mathematically equivalent to WFD, with the exception of how the interpersonal network is constructed. Where as in WFD the person-to-person network is built out of how many formal interactions team-members have, the person-to-person relationships in CWD are built based on the amount tasks assigned to individuals relate.

CWD is defined for a given task (or code segment). CFD, is an indirect index of dependency because it incorporates inter person dependencies where a task is the central object of dependency. CFD incorporates both people and tasks making it bivariate. Degree centrality is the main network characteristic used to calculate CFD. CFD is a bivariate individual level index of indirect dependency characterized by degree centrality. 

The limitations and advantages to CWD are similar to those of WFD. The main differentiating point is that CWD will but built off of assessment of informal task relatedness where as WFD will be built off of formalized inter-person work flow relationships. They may have drastically different implications to outcomes, and therefore there is merit in calculating both indices.

#### Clustering of Logical Dependency (CLD)
When writing code some files tend to be adjusted together, likewise in general a team may have some tasks which are linked (not necessarily in a pre-requisite type of way). There is no specific rule that says the two tasks should be related, but there is a hidden type of dependency. These relationships have been called Logical dependencies in software development. CLD is an index of dependency that analysis how often tasks dependent on a central task are dependent with each other. According to CLD, the more logical dependencies cluster, the more interdependent the tasks are.

CLD is calculated as the ratio of links between neighbors of a central task, to possible links between neighbors of the central task. CLD is maximized when every task a task is related to are all related to each other. CLD is minimized when there are no inter-connections between the tasks a central task is dependent on. Theoretically the more dependencies are clustered the heavier the impact of those dependencies.

CLD is an individual level index of dependency. CLD incorporates indirect dependencies. CLD is specific to just task (code), and therefore univariate. The central network characteristic for CLD is clustering.

#### Number of Logical Dependencies (NLD) 
NLD is an index of the total number of logical dependencies a file has. This is closely related to syntactic dependency with the difference in the type of dependency relationships being counted. NLD is applied to the same dependency relationships that CLD is, and is only different in that it uses a different network characteristic. 

NLD is an individual level index of dependency. NLD only accounts for direct dependency relationships. Logical dependencies do not account for people so NLD is entirely univariate. NLD is simply a count of logical dependences and is thus related to degree centrality. NLD is structurally equivalent to syntactic dependency.