---
output: pdf_document
title: Dependency Intro
---
# Suggestions
The six categories of dependency index describe by the proposed taxonomy provide a powerful way to organize and focus research. We propose that each category of index has a different conceptualization of dependency. Theoretical conceptualization of dependency should match those conceptualizations inherent in an index. We will briefly describe various theoretical conceptualizations of dependency and discuss appropriate measures.

## Dependency as an additive characteristic of teams and individuals.
It is possible to theoretically consider the level of dependency within a team as some function of the sum total of all dependent relationships. This conceptualization does not focus on how these dependency relationships are distributed throughout the team but instead focuses on the number and strength of the dependencies. For example, a team where most individuals relied on almost everyone else would be expected to have strong dependency according to this conceptualization. Teams, where only a few dependencies exist, would likewise have a weak dependency. This conceptualization  does not pay attention to factors such as if the dependency relationships form a chain (i.e person A depends on B, and person B depends on C, etc.), or if they cluster together (i.e A and B and C are all dependent on each other and D, E and F are all dependent on each other). For research that takes this summative approach to dependency, we suggest the use of magnitude measures of dependency. Typically these measures will give a good picture of the 'amount' of dependency present, without implying importance in inter-relations or sequential patterns that other measures will inherently measure. If the focus if on dependency as a characteristic of teams a team level index should be used and if the focus is on individuals an individual level index should be used.

##Dependency in failure propagation in a team
Dependency can be a mechanism for failure propagation in a team. The core concept here is that each dependency relationship makes up a link whereby some failure in the system can lead to other failures. If everyone in a team requires everyone else to perform well in order to themselves perform well, one person not doing their job will cause the entire team to fail. On the other hand, if there are no dependency relationships within a team, no one's failure will impact anyone else. If failure propagation is the focus of a study or the theoretical mechanism in question, it is important to keep this in mind in choosing measures of dependency. 

Typically questions of failure propagation will be team level considerations, though it is possible that the question is how much is an individual susceptible to other's failures. We will discuss this bellow. While increased values of magnitude measures would be associated with a greater propensity for failure propagation in a team, we suggest that the other measures may encode structural considerations important to how failure may propagate. For example, inter-relatedness measures such as those based on clustering may be able to measure how likely failures will clump together causing catastrophic failures in groups of related individuals or tasks while largely not impacting others. Sequential indices can, on the other hand, predict the number of pathways by which failure can propagate and how large (how many things are impacted) the impact of failure could be. 
Considering each category of index measures a unique characteristic, we suggest using one of each category in cases where failure propagation is important.

## Dependency as a measure of critical team roles or critical tasks
Some studies may be less interested in how much a team is likely to propagate failures, than how important one specific individual is. I identifying critical team members may have drastic impacts on team performance, because once identified steps can be taken to ensure critical team members are not overloaded and protected from other factors that may increase the likelihood of making a mistake. As with team failure propagation work, magnitude measures may be helpful in identifying critical individuals. For example, the individual with the greatest number of dependencies are ones you really do not want to fail, and likely the ones most likely to fail. Sequential measures are similarly important because they can be predictive of how many tasks or people downstream depend on an individual, however, inter-related measures are less meaningful in this case. We suggest this type of research using a magnitude and sequential index of individual dependency.


# Discussion
In this paper, we have discussed the importance of dependency to teams and team outcomes. Not only is dependency a definitional requirement of teams, but is a powerful tool for differentiating teams, and has significant impacts on team outcomes. Despite continual acknowledgement of dependency's importance to outcomes studied by organizational scientist, there has been no clear definition of dependency or framework that can differentiate between measures of dependency.

We contribute to the theory of dependency by describing how dependencies form relationships between objects and sources of dependency such that performance of the object is influenced by performance of the source. We further contributed to the theory of dependencies by describing how these dependency relationships within a dependency network could illustrate possible sources of failure or success in a team system. These relationships can also demonstrate how team members can facilitate or inhibit a team's overall performance. Most significantly, we have contributed to organizational theory by providing a taxonomy that can be used to describe dependency indices. This lexicon will be a tremendous stepping stone for future research and theory development of organizational dependency. This will also help to resolve potential conflicting results and promote unity in future dependency research communications.

It is important to note that many of the indices discussed in this paper could be applied to various forms of dependency, providing means to evaluate various facets of dependency in teams. These indices do not necessarily only work for the exact type of dependency they were originally designed for. There are various modes for assessing a team's dependency. We suggest that there is value in coordinating structural measures of dependency with self-report and observational measures. We specifically advocate for more use of structural measures of dependency. While self-report and observational measures may be fairly quick and easy, structural measures may be able to help explain team processes in a way the traditional measures are incapable of doing. 

We have not tested or validated the indices reviewed in this article and are therefore hesitant to make a definitive assessment of which measures should be used and when. We do suggest that a researcher identify which measures most closely fit with their goals and apply these indices. For example, a researcher interested in an individual level measure of dependency that accounts for relationships between person and task would find that IPCl and IPCd are likely the best options, depending on if the volume or the structure of dependency is more important to the researcher. We recognize that the list of indices we have provided is short and may not provide the index needed in some situations. We hope that this framework will encourage the investigation and development of new dependency indices.

This paper has only briefly discussed the question of what dependency is. We have provided a definition of dependency and introduced a network conceptualization of dependency. It appears that  dependency can be interpreted as a network in a very natural way. We suggest that this network conceptualization may lead to formalized models of dependency, which could be used to further clarify the impacts of dependency.

## Future Work
This paper represents the beginning of a long task in distinguishing and describing dependency in organizations and their outcomes. While we feel that the taxonomy presented here covers the main characteristics of dependency indices, this framework is by no means comprehensive nor complete. There are likely many more characteristics of dependency indices worth considering. We suggest that future research may identify dimensions that should be incorporated into the dependency taxonomy.

A systematic study of different types of dependency is an area of research that is greatly needed. We have proposed that dependencies are relationships that form networks between them. A thorough investigation of this theoretical interpretation of dependency and its implications is needed. Specifically, a review of different forms of dependency and the outcomes they are linked to. While the taxonomy provided in this paper can be used to distinguish potential types of dependency, it is focused primarily on distinguishing indices of dependency, and further investigation into how to categorize types of dependency is necessary. 

We further suggest that future work studying dependency will likely focus on dependency networks. The network conceptualization of dependency provides a formalized framework  for dependency relationships and appears to be a natural fit. The theoretical implications of a network perspective of dependency are rich and promising.

We find it shocking that despite the large number of papers that reference the importance of dependency, there has been, to our knowledge, no systematic review of the literature regarding the impacts of dependency. It is our hope that the taxonomy provided in this paper will aid the study and review of organizational dependencies impacts. Specifically, we hope that a future categorization of dependency types will help drive a review that is able to systematically identify what the impacts of differing forms of organizational dependency are.

## Conclusion

We have contributed to the organizational sciences theory by providing a theoretical conceptualization of what dependencies are and how they form networks. We have furthermore contributed to organizational sciences by providing a taxonomy for indices of dependency and briefly reviewing and identifying examples of dependency indices.

Organizational dependency is not only an enormously important topic, but also a very promising avenue for research. There appears to be a bright future in the study of organizational dependency.
