---
output: pdf_document
---
# Discussion

Structural interdependence is one of the key features that drives organizational activity. Few theories on team behavior, leadership, or effective unit performance find merit without acknowledging some aspect of task workflows, the connections among actors, resource partitioning, or the amount of congruence among individual and group goals. Researchers have even gone so far as to say that the possibility for a group to be greater than the sum of its parts is a direct function of interdependence [@tziner1985effects]. Given its importance, the field has seen an array of measures and theoretical indices emerge, all capturing somewhat different aspects. In the 60's, 70's, 80's, and 90's a range of indices based on task and person matrices were advanced, but recently the field's dominate method for assessing interdependence has been self reports. Our paper reflected on this material, organized the measures into a coherent taxonomy so that future work can more readily apply the various measures, and raised questions and assumptions to facilitate sound practice within interdependence measurement. Moreover, discussion regarding interdependence indices and measurement is far behind what we have witnessed in related areas such as agreement indices [e.g., @kozlowski1992disagreement] or fit statistics. The purpose of this paper is to call attention to this domain and ignite research in this area. 

Throughout, we acknowledged tensions in dependence measurement. We close by providing clear recommendations on how researchers should represent and interpret dependence in their work. 

First, researchers should think hard about the purpose of their study and the inference they are trying to make before selecting an interdependence measure. Do not choose a measure simply because it is easy to find or convenient. We provide references and example items for a large list of measures that should help researchers identify a measure that captures what they are after. Without clarity regarding the process or construct researchers wish to make inferences about, finding an adequate measure or way to operationalize it is unwarranted. Our tables can be used to identify interdependence measures of various types at different levels. If, for example, the interest is initiated interdependence at the individual level, a researcher could use the subscale provided by Morgeson and Humphrey (2006), whereas measures provided in Table 2 on outcome interdependence can be used for researchers interested in the degree to which the outcomes of taskwork are measured, rewarded, and communicated so as to emphasize collective outputs rather than individual contributions. Moreover, Arthur et al. (2012) provide a particularly useful scale when researchers have already conducted (or have the resources to conduct) a task analysis and can ask subjects workflow questions regarding each task that they complete. 

Second, researchers should align theory with measurement. Inferences regarding levels that are not measured are said to be misspecified. @rousseau1985issues originally spoke about this issue with respect to individuals and organizations, where misspecification referred to collecting individual-level data and using it to make (spurious) inferences about organizations. The same reasoning applies to tasks and jobs. @wong_development_1991 state that a job "is an aggregation of tasks assigned to a worker. When the same set of tasks are performed by more than one worker, those workers ... have the same job" (p. 825). Misspecification occurs when researchers collect task-level data but make inferences about jobs -- an aggregated, higher-level construct -- or when researchers collect job or person-level data but direct their inferences down a level and speak about tasks. If the theory and reasoning applies to jobs, then jobs should be the referent within the measurement device, and if the theory and reasoning refer to tasks, then tasks should be the measured unit. 

Finally, our review and tables provide clarity on dependence interpretation. We refer readers to the original sources if they wish to learn more about computing a specific index, our focus is on interpreting various indices. The self-report measures are straight-forward: a high score on a task interdependence device indicates greater perceived workflow requirements, precedence relationships, or resource partitioning than a low score, whereas outcome interdepenedence self-reports assess the extent to which goals or rewards are (perceived to be) determined by collective rather than individual contributions. The structrual interdependence indices are less common and so are not as familiar, but they are interpreted as follows. Indices provided by O'Brien (1968), Wood (1986), and Oeser and O'Brien (1967) capture precedence relationships: a greater value indicates that tasks must be completed before others, whereas a low value indicates that tasks can be completed independently. Indices provided by O'Brien (1968) and Oeser and Frank (1962, 1964) reflect joint taskwork: a greater value indicates that tasks are completed simultaneously by a greater number of individuals, whereas a low score indicates that each task is completed by a single or few individuals. Syntactic, workflow, and logical dependency all capture the extent to which scripts (tasks) require material from other scripts (tasks). A high value of syntactic dependency, compared to a low value, means that one script (task) uses material from many other scripts (tasks). A high value of logical dependency, compared to a low value, means that a given script (task) requires other scripts (tasks) to be updated within the same time window -- programmers call these time windows commits, but they could represent any timespan of interest. A high value of workflow dependency, compared to a low value, indicates that a given script (task) undergoes changes by someone with many connections to other people and their tasks. The NK model of interdependence (Lenox et al., 2007) captures the number of configurations as tasks begin to depend on one another. A high value indicates that there are many task orientations, each potentially resulting in different outcomes for the individual, group, or organization. Indices provided by Victor and Blackburn (1987) assess outcome interdependence. A high value of their index of dependence means that outcomes for a given individual are determined by the tasks of others in his or her unit, whereas a low value reflects independent rewards -- any changes in rewards or outcomes stem from the individual's tasks only. Moving to the index of correspondence, a high value reflects overlap among rewards determined by one's own tasks with rewards determined by other's tasks, whereas a low value means that rewards determined by one's own tasks do not align with rewards determined by other's tasks. In other words, a low value reflects incentives to act only on tasks that are rewarded at the individual level. 





