---
title: "Dependency_notes"
author: "Daniel Griffin"
date: "November 8, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Notes on possible dependency directions
My original idea was to go though and identify a generalized way at looking at dependency in terms of the state required for a task to be completed. 

After talking though it, we think that a paper that lists current measures of dependency and describes where they are used could be more useful. 

After taking the review of dependency indices, we could move on to do quite a bit in that space. Nothing really exists there. A generalized definition and conceptualization of dependency could be powerful, but we probably need to lay the foundation with a review article first.

On Thursday the 8the we talked more about it. The current direction is to really focus on forming a framework for distinguishing and evaluating different forms of dependency indices. We have a lot of work as far as literature review to know where this will go.

11/15/2018
Need to have a less aggressive tone (i.e. do not use the word failed). Say something along the lines of "A bunch of awesome people have talked about it, but we don't have an index of it. Critics are generally not well received, praise what has come before". Really focus on index, All these people (Edwardo Sales). This notion is ubiquitous. They all talk about dependency as a core construct, but we do not have a clear index of dependency. 

 - Avoid going too deep into what is dependency? Use a very generic definition (do this after working with indices). We may think about doing a general dependency definition / review paper. But this paper is really focused on starting the process. A list of indices will likely be well received. and achieves our goal of making the argument of why we need it in the general paper.

 - Self report measure of dependency (back up behavior)

 - Really work on unifying literature, not confrontational.

 - Probably want to take psychological perceptions off the board. Avoid self-report. 

Applicable to conflict within roles

Find equations

Look for dependency in network science. (Connectivity, edge connectivity, )