---
output: pdf_document
---
# Discussion

Structural interdependence is one of the key features that drives organizational activity. Few theories on team behavior, effective unit performance, or leadership find merit without acknowledging some aspect of task workflows, the connections among actors, resource partitioning, or the amount of congruence among individual and group goals. Researchers have even gone so far as to say that the possibility for a group to be greater than the sum of its parts is a direct function of interdependence [@tziner1985effects]. Given its importance, the field has seen an array of measures and theoretical indices emerge, all capturing somewhat different aspects. In the 60's, 70's, 80's, and 90's a range of indices based on task and person matrices were advanced, but recently the field's dominate method for assessing interdependence has been self reports. Our paper reflected on this material, organized the measures into a coherent taxonomy so that future work can more readily apply the various measures, and raised questions and assumptions to facilitate sound practice within interdependence measurement. Moreover, discussion regarding interdependence indices and measurement is far behind what we have witnessed in related areas such as agreement indices [e.g., @kozlowski1992disagreement] or fit statistics. The purpose of this paper is to call attention to this domain and ignite research in this area. 