---
output: pdf_document
---

The nature of work is changing such that the connections between tasks and actors are increasingly relevant levers for understanding and benefiting from human capital. Five times as many Americans are employed in service jobs compared to those in manufacturing and production [@ford_service-dominant_2008; @parker_future_2001], signaling the shift from a manufacturing economy of additive tasks to a market economy of knowledge and service in which organizational success is driven by the complex interplay between customers, employees, and stakeholders. Changes in information, communication, and transportation technology fueled flatter firm hierarchies, virtual and telework, and teams as the building blocks of modern organizations [@mathieu_review_2014] where employees must manage work flows and coordinate their activities to perform at high levels [@kozlowski_groups_2012]. Organizational scientists now emphasize questions about connections and interdependence among employees who collaborate with and receive feedback from their coworkers [@grant_7_2009] because the interplay of task and social relations among team members is thought to either relate to outcomes such as collective efficacy, cohesion, behavioral processes, and performance [@courtright_structural_2015] or create the context in which team behaviors unfold through time [@marks_temporally_2001; @baard_performance_2014]. Understanding the nature of dependence among actors will enable organizations to better design, train, develop, and motivate personnel for effective teamwork, whereas endeavors that fail to consider interdependence have "little relevance to building knowledge in the work groups and team literatures" [@kozlowski_work_nodate, p. 363].

Interdependence or dependency (defined later) has received increasing attention among organizational researchers, and most tie their work in some way to the notions of Thompson's (1967) task workflows, Mohr's (1971) writing on the extent to which individuals perceive that they have "one person" jobs, or Penning's (1975) bases of interconnectedness. Bell and Kozlowski [-@bell_typology_2002] present a typology of virtual teams where interdependency is one of the main features distinguishing different team types; @morgeson2012work and @grant_7_2009 review the work design literature and present task interdependence as a key feature for understanding organizational behavior; @kiggundu_task_1981 presents a theory of how interdependence relates to feelings of responsibility to one's work; @lenox_interdependency_2007 use interdependence in their theory on why firms rise and fall within an industry over time; and Puranam, Raveendran, and Knudsen's  [-@puranam_organization_2012] theory incorporates organization design, information processing, and interdependence. Empirical studies on interdependence, both as a predictor and outcome, slowed after initial reports by @ven_determinants_1976 and @cheng_interdependence_1983 but have recently reemerged in the literature [e.g., @de_dreu_cooperative_2007; @grant_significance_2008; @hertel_managing_2004; @lee_why_2018].  

Although these reviews, theories, meta-analyses, and empirical studies have increased our understanding of interdependence in organizations and teams, its measurement and operationalization have yet to be unified or organized. Items sometimes measure interdependence without attending to (and perhaps confounding) its various directions, such as initiated and received [@kiggundu_task_1981] or reciprocal [@pearce_task_nodate]. There are different domains that it can apply to, such as role, task, or outcome dependence [@wageman_interdependence_1995], different levels of abstraction, such as whether the measure applies to the individual, dyad, group, or firm [@mansfield_interdependence_2003], and it has been proposed as a way to create typologies both for teams and tasks [@lee_team_2015]. Many of these issues have been refined conceptually, especially within a recent meta-analysis by Courtright et al. [-@courtright_structural_2015], but the literature contains little guidance on where the field stands with respect to interdependence measurement. Moreover, there are theoretical indices, observational measures, self reports, discrete task counts, workflow images used in supervisor interviews, formal equations for agent-based models, network indices, and algorithms for computing dependence based on resource exchanges all as methods of indicating the level of interdependence in a given setting. The purpose of this paper is to organize this material, provide a taxonomy of interdependence measures, and link measures to specific purposes so that future research can appropriately align measurement with theory. 

The contributions of this paper are as follows. First, we provide a resource for identifying various interdependence measures and their purpose. Gathering the array of measures into a single location allows us to better understand what they capture and how they can be used, notice inconsistencies and areas for improvement, and provides directions for future research. Each of these components will be discussed in this paper. By organizing and reflecting, we are also able to place attention on old indices that are useful but have been underappreciated. Interdependence measurement today is dominated by self reports, but there were a number of relevant theoretical indices proposed in the 60's, 70's, and 80's that we hope to re-highlight. Second, we draw attention to aggregation and the multi-level nature of interdependence. As discussed later, there is a growing emphasis on initiated, received, and reciprocal interdependence as various arrangements at play in a task environment. Although researchers acknowledge that these constructs are related, their measurement occurs without discussion about the appropriate way to aggregate or compile one construct to another. We recast this discussion in terms of Chan's [-@chan_functional_1998] composition framework and multi-level theory to better appreciate the various levels that interdependence can subsume. Third, any clarity that comes from interdependence measurement should advance theory in this area. By reflecting on how interdependence is operationalized and measured, new ideas emerge that we hope ignites better theory. Seeing all of the measures at once also helps identify confounds that merit theoretical scrutiny in future work. Finally, our paper is a launching point for research, argument, and hopefully eventual consensus on the merits of various interdependence indices. Our literature has witnessed heated debates about agreement indices, structural equations modeling fit statistics, difference scores, diversity indices, and how to appropriately represent person-environment fit. All of these areas worked out best methods, practices, and interpretations of various indices. Our paper is a signal that interdependence deserves something similar. 

We begin by discussing interdependence and its various dimensions. Next, we present our taxonomy and way of organizing the interdependence measures and indices. After unpacking and reviewing the material, we discuss challenges, provide recommendations, and point to next steps for research. 

# Structural Interdependence

Interdependence has been discussed across many reviews in fields ranging from organizational psychology to political science, strategy, and management [@wegman_placing_2018; @lenox_interdependency_2007; @dalton_organization_1980; @fan_measurement_2000]. Theoretical clarity on its different forms was provided in a meta-analysis by Courtright et al. (2015); we follow their organization to introduce this material. Structural interdependence refers to features of the team -- such as resources and workflows as well as goal and reward systems that can be deliberately manipulated by team leaders and members -- that define the interconnectedness of team members [@wageman_interdependence_1995]. Courtright et al. (2015) note that,

>> team members and leaders choose low [structural] interdependence when they structure tasks on an individual basis with a pooled product, when they form the team with resources redundant across team members, or when they establish goal and reward systems that primarily emphasize individual contributions over collective outputs. In contrast, they choose high [structural] interdependence when members simultaneously work on all aspects of the task, when they intentionally form groups with members processing varied access to resources, or when they establish goal and reward systems that primarily emphasize collective outputs. (p. 3). 

Structural interdependence is distinct from teamwork behaviors such as planning, monitoring progress, confidence building, and backup behaviors [@marks_temporally_2001], which are referred to collectively as behavioral processes in the teams literature [@dechurch2010cognitive]. @shea1987groups and @wageman_interdependence_1995 referred to actual team behaviors and interactions as an alternative form of interdependence, called behavioral interdependence, meaning, for example, if workers on assembly line "A" interact more than workers on assembly line "B" then those in "A" have greater behavioral interdependence. But Courtright et al. (2015) note that this idea is largely captured within the behavioral processes described in teams reviews. Our paper focuses on measures and theoretical indices for structural interdependence. 

# Forms of Structural Interdependence - Task and Outcome

Different labels exist for the various dimensions of structural interdependence, but they can largely be classified within two areas: task and outcome interdependence. Task interdependence refers to "the degree to which taskwork is designed so that members depend upon one another for access to resources and create workflows that require coordinated action" (Courtright et al., 2015, p. 4). It captures what @mathieu_team_2008 called means interdependence, what @naylor1969task called work structure, Shaw's [-@shawscaling] cooperation requirements dimension, what @ven_determinants_1976, @mccann_approach_1979, and @thompson2017organizations called task interdependence or the notion of workflow patterns, what @dechurchmts call process interdependence, what @arthur_team_2012 called team relatedness and workflow, O'Brien's [-@obrien_measurement_1968] notions of collaboration and coordination, and the dimensions of role theory outlined by @oeser1962mathematical. Research in this area focuses on how tasks are divided among the group, the precedence relationships among tasks and roles, the extent to which members depend on one another for skills, data, materials, information, and other resources, the combination of task accomplishments into a final product, the extent to which members work individually versus in a group, and the flow of materials across members. 

Outcome interdependence refers to "the degree to which the outcomes of taskwork are measured, rewarded, and communicated at the group level so as to emphasize collective outputs rather than individual contributions" (Courtright et al., 2015, p. 4). It captures what @puranam_organization_2012 called agent interdependence, what @barrick_moderating_2007 called psychological interdependence, what @pennings_interdependence_1975 called social interconnectedness, what @tjosvold_dynamics_1986 called goal interdependence, and the notions of payoff differences with respect to what @victor_interdependence_1987 called reflexive, fate, and behavioral control. Research in this area focuses on whether goals and feedback are provided at the individual versus team level, the nature of rewards and whether they are contingent on individual or group contributions, and how performance is aggregated and communicated back to the actors. 

# Taxonomy and Classification

Although researchers operationalize interdependence in a variety of ways, they can largely be partitioned into two domains: self reports and theoretical indices. Self reports are administered to team members, leaders, or supervisors and the individuals are then asked to indicate their perceived interdependence, whereas theoretical indices are formulas or methods for researchers to compute values of interdependence based on theorized or observed workflow patterns, goal structures, or task interactions. Within each of these broad discussion areas (i.e., self reports and theoretical indices) we discuss task and outcome interdependence and also further distinctions such as initiated and received (defined below) interdependence, whether the measure is used at the individual or team level, example items and uses, and provide recommendations, critiques, and research agendas for future work. 